// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cachemocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGenericCache creates a new instance of MockGenericCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenericCache[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenericCache[T] {
	mock := &MockGenericCache[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenericCache is an autogenerated mock type for the GenericCache type
type MockGenericCache[T any] struct {
	mock.Mock
}

type MockGenericCache_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockGenericCache[T]) EXPECT() *MockGenericCache_Expecter[T] {
	return &MockGenericCache_Expecter[T]{mock: &_m.Mock}
}

// Get provides a mock function for the type MockGenericCache
func (_mock *MockGenericCache[T]) Get(key string) (T, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 T
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (T, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) T); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockGenericCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGenericCache_Get_Call[T any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockGenericCache_Expecter[T]) Get(key interface{}) *MockGenericCache_Get_Call[T] {
	return &MockGenericCache_Get_Call[T]{Call: _e.mock.On("Get", key)}
}

func (_c *MockGenericCache_Get_Call[T]) Run(run func(key string)) *MockGenericCache_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGenericCache_Get_Call[T]) Return(v T, b bool) *MockGenericCache_Get_Call[T] {
	_c.Call.Return(v, b)
	return _c
}

func (_c *MockGenericCache_Get_Call[T]) RunAndReturn(run func(key string) (T, bool)) *MockGenericCache_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockGenericCache
func (_mock *MockGenericCache[T]) Set(key string, data T, expiration time.Duration) {
	_mock.Called(key, data, expiration)
	return
}

// MockGenericCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockGenericCache_Set_Call[T any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - data T
//   - expiration time.Duration
func (_e *MockGenericCache_Expecter[T]) Set(key interface{}, data interface{}, expiration interface{}) *MockGenericCache_Set_Call[T] {
	return &MockGenericCache_Set_Call[T]{Call: _e.mock.On("Set", key, data, expiration)}
}

func (_c *MockGenericCache_Set_Call[T]) Run(run func(key string, data T, expiration time.Duration)) *MockGenericCache_Set_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGenericCache_Set_Call[T]) Return() *MockGenericCache_Set_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockGenericCache_Set_Call[T]) RunAndReturn(run func(key string, data T, expiration time.Duration)) *MockGenericCache_Set_Call[T] {
	_c.Run(run)
	return _c
}
