// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package clientsmocks

import (
	"context"

	"github.com/nicolas-martin/dankfolio/backend/internal/model/blockchain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGenericClientAPI creates a new instance of MockGenericClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenericClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenericClientAPI {
	mock := &MockGenericClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenericClientAPI is an autogenerated mock type for the GenericClientAPI type
type MockGenericClientAPI struct {
	mock.Mock
}

type MockGenericClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenericClientAPI) EXPECT() *MockGenericClientAPI_Expecter {
	return &MockGenericClientAPI_Expecter{mock: &_m.Mock}
}

// ExecuteSwap provides a mock function for the type MockGenericClientAPI
func (_mock *MockGenericClientAPI) ExecuteSwap(ctx context.Context, rawQuote any, userAddress blockchain.Address, signedTxIfNeeded []byte) (blockchain.Signature, error) {
	ret := _mock.Called(ctx, rawQuote, userAddress, signedTxIfNeeded)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteSwap")
	}

	var r0 blockchain.Signature
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, blockchain.Address, []byte) (blockchain.Signature, error)); ok {
		return returnFunc(ctx, rawQuote, userAddress, signedTxIfNeeded)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, blockchain.Address, []byte) blockchain.Signature); ok {
		r0 = returnFunc(ctx, rawQuote, userAddress, signedTxIfNeeded)
	} else {
		r0 = ret.Get(0).(blockchain.Signature)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any, blockchain.Address, []byte) error); ok {
		r1 = returnFunc(ctx, rawQuote, userAddress, signedTxIfNeeded)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenericClientAPI_ExecuteSwap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteSwap'
type MockGenericClientAPI_ExecuteSwap_Call struct {
	*mock.Call
}

// ExecuteSwap is a helper method to define mock.On call
//   - ctx context.Context
//   - rawQuote any
//   - userAddress blockchain.Address
//   - signedTxIfNeeded []byte
func (_e *MockGenericClientAPI_Expecter) ExecuteSwap(ctx interface{}, rawQuote interface{}, userAddress interface{}, signedTxIfNeeded interface{}) *MockGenericClientAPI_ExecuteSwap_Call {
	return &MockGenericClientAPI_ExecuteSwap_Call{Call: _e.mock.On("ExecuteSwap", ctx, rawQuote, userAddress, signedTxIfNeeded)}
}

func (_c *MockGenericClientAPI_ExecuteSwap_Call) Run(run func(ctx context.Context, rawQuote any, userAddress blockchain.Address, signedTxIfNeeded []byte)) *MockGenericClientAPI_ExecuteSwap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 blockchain.Address
		if args[2] != nil {
			arg2 = args[2].(blockchain.Address)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGenericClientAPI_ExecuteSwap_Call) Return(signature blockchain.Signature, err error) *MockGenericClientAPI_ExecuteSwap_Call {
	_c.Call.Return(signature, err)
	return _c
}

func (_c *MockGenericClientAPI_ExecuteSwap_Call) RunAndReturn(run func(ctx context.Context, rawQuote any, userAddress blockchain.Address, signedTxIfNeeded []byte) (blockchain.Signature, error)) *MockGenericClientAPI_ExecuteSwap_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountInfo provides a mock function for the type MockGenericClientAPI
func (_mock *MockGenericClientAPI) GetAccountInfo(ctx context.Context, address blockchain.Address) (*blockchain.AccountInfo, error) {
	ret := _mock.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountInfo")
	}

	var r0 *blockchain.AccountInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, blockchain.Address) (*blockchain.AccountInfo, error)); ok {
		return returnFunc(ctx, address)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, blockchain.Address) *blockchain.AccountInfo); ok {
		r0 = returnFunc(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*blockchain.AccountInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, blockchain.Address) error); ok {
		r1 = returnFunc(ctx, address)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenericClientAPI_GetAccountInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountInfo'
type MockGenericClientAPI_GetAccountInfo_Call struct {
	*mock.Call
}

// GetAccountInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - address blockchain.Address
func (_e *MockGenericClientAPI_Expecter) GetAccountInfo(ctx interface{}, address interface{}) *MockGenericClientAPI_GetAccountInfo_Call {
	return &MockGenericClientAPI_GetAccountInfo_Call{Call: _e.mock.On("GetAccountInfo", ctx, address)}
}

func (_c *MockGenericClientAPI_GetAccountInfo_Call) Run(run func(ctx context.Context, address blockchain.Address)) *MockGenericClientAPI_GetAccountInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 blockchain.Address
		if args[1] != nil {
			arg1 = args[1].(blockchain.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenericClientAPI_GetAccountInfo_Call) Return(accountInfo *blockchain.AccountInfo, err error) *MockGenericClientAPI_GetAccountInfo_Call {
	_c.Call.Return(accountInfo, err)
	return _c
}

func (_c *MockGenericClientAPI_GetAccountInfo_Call) RunAndReturn(run func(ctx context.Context, address blockchain.Address) (*blockchain.AccountInfo, error)) *MockGenericClientAPI_GetAccountInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockGenericClientAPI
func (_mock *MockGenericClientAPI) GetBalance(ctx context.Context, address blockchain.Address, commitment string) (*blockchain.Balance, error) {
	ret := _mock.Called(ctx, address, commitment)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *blockchain.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, blockchain.Address, string) (*blockchain.Balance, error)); ok {
		return returnFunc(ctx, address, commitment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, blockchain.Address, string) *blockchain.Balance); ok {
		r0 = returnFunc(ctx, address, commitment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*blockchain.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, blockchain.Address, string) error); ok {
		r1 = returnFunc(ctx, address, commitment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenericClientAPI_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockGenericClientAPI_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - address blockchain.Address
//   - commitment string
func (_e *MockGenericClientAPI_Expecter) GetBalance(ctx interface{}, address interface{}, commitment interface{}) *MockGenericClientAPI_GetBalance_Call {
	return &MockGenericClientAPI_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, address, commitment)}
}

func (_c *MockGenericClientAPI_GetBalance_Call) Run(run func(ctx context.Context, address blockchain.Address, commitment string)) *MockGenericClientAPI_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 blockchain.Address
		if args[1] != nil {
			arg1 = args[1].(blockchain.Address)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGenericClientAPI_GetBalance_Call) Return(balance *blockchain.Balance, err error) *MockGenericClientAPI_GetBalance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockGenericClientAPI_GetBalance_Call) RunAndReturn(run func(ctx context.Context, address blockchain.Address, commitment string) (*blockchain.Balance, error)) *MockGenericClientAPI_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestBlockhash provides a mock function for the type MockGenericClientAPI
func (_mock *MockGenericClientAPI) GetLatestBlockhash(ctx context.Context) (blockchain.Blockhash, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBlockhash")
	}

	var r0 blockchain.Blockhash
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (blockchain.Blockhash, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) blockchain.Blockhash); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(blockchain.Blockhash)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenericClientAPI_GetLatestBlockhash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestBlockhash'
type MockGenericClientAPI_GetLatestBlockhash_Call struct {
	*mock.Call
}

// GetLatestBlockhash is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGenericClientAPI_Expecter) GetLatestBlockhash(ctx interface{}) *MockGenericClientAPI_GetLatestBlockhash_Call {
	return &MockGenericClientAPI_GetLatestBlockhash_Call{Call: _e.mock.On("GetLatestBlockhash", ctx)}
}

func (_c *MockGenericClientAPI_GetLatestBlockhash_Call) Run(run func(ctx context.Context)) *MockGenericClientAPI_GetLatestBlockhash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGenericClientAPI_GetLatestBlockhash_Call) Return(blockhash blockchain.Blockhash, err error) *MockGenericClientAPI_GetLatestBlockhash_Call {
	_c.Call.Return(blockhash, err)
	return _c
}

func (_c *MockGenericClientAPI_GetLatestBlockhash_Call) RunAndReturn(run func(ctx context.Context) (blockchain.Blockhash, error)) *MockGenericClientAPI_GetLatestBlockhash_Call {
	_c.Call.Return(run)
	return _c
}

// GetSwapQuote provides a mock function for the type MockGenericClientAPI
func (_mock *MockGenericClientAPI) GetSwapQuote(ctx context.Context, fromToken blockchain.Address, toToken blockchain.Address, amount string, userAddress blockchain.Address, slippageBps int, platformFeeBps int) (*blockchain.TradeQuote, error) {
	ret := _mock.Called(ctx, fromToken, toToken, amount, userAddress, slippageBps, platformFeeBps)

	if len(ret) == 0 {
		panic("no return value specified for GetSwapQuote")
	}

	var r0 *blockchain.TradeQuote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, blockchain.Address, blockchain.Address, string, blockchain.Address, int, int) (*blockchain.TradeQuote, error)); ok {
		return returnFunc(ctx, fromToken, toToken, amount, userAddress, slippageBps, platformFeeBps)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, blockchain.Address, blockchain.Address, string, blockchain.Address, int, int) *blockchain.TradeQuote); ok {
		r0 = returnFunc(ctx, fromToken, toToken, amount, userAddress, slippageBps, platformFeeBps)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*blockchain.TradeQuote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, blockchain.Address, blockchain.Address, string, blockchain.Address, int, int) error); ok {
		r1 = returnFunc(ctx, fromToken, toToken, amount, userAddress, slippageBps, platformFeeBps)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenericClientAPI_GetSwapQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSwapQuote'
type MockGenericClientAPI_GetSwapQuote_Call struct {
	*mock.Call
}

// GetSwapQuote is a helper method to define mock.On call
//   - ctx context.Context
//   - fromToken blockchain.Address
//   - toToken blockchain.Address
//   - amount string
//   - userAddress blockchain.Address
//   - slippageBps int
//   - platformFeeBps int
func (_e *MockGenericClientAPI_Expecter) GetSwapQuote(ctx interface{}, fromToken interface{}, toToken interface{}, amount interface{}, userAddress interface{}, slippageBps interface{}, platformFeeBps interface{}) *MockGenericClientAPI_GetSwapQuote_Call {
	return &MockGenericClientAPI_GetSwapQuote_Call{Call: _e.mock.On("GetSwapQuote", ctx, fromToken, toToken, amount, userAddress, slippageBps, platformFeeBps)}
}

func (_c *MockGenericClientAPI_GetSwapQuote_Call) Run(run func(ctx context.Context, fromToken blockchain.Address, toToken blockchain.Address, amount string, userAddress blockchain.Address, slippageBps int, platformFeeBps int)) *MockGenericClientAPI_GetSwapQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 blockchain.Address
		if args[1] != nil {
			arg1 = args[1].(blockchain.Address)
		}
		var arg2 blockchain.Address
		if args[2] != nil {
			arg2 = args[2].(blockchain.Address)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 blockchain.Address
		if args[4] != nil {
			arg4 = args[4].(blockchain.Address)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		var arg6 int
		if args[6] != nil {
			arg6 = args[6].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockGenericClientAPI_GetSwapQuote_Call) Return(tradeQuote *blockchain.TradeQuote, err error) *MockGenericClientAPI_GetSwapQuote_Call {
	_c.Call.Return(tradeQuote, err)
	return _c
}

func (_c *MockGenericClientAPI_GetSwapQuote_Call) RunAndReturn(run func(ctx context.Context, fromToken blockchain.Address, toToken blockchain.Address, amount string, userAddress blockchain.Address, slippageBps int, platformFeeBps int) (*blockchain.TradeQuote, error)) *MockGenericClientAPI_GetSwapQuote_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenAccountsByOwner provides a mock function for the type MockGenericClientAPI
func (_mock *MockGenericClientAPI) GetTokenAccountsByOwner(ctx context.Context, ownerAddress blockchain.Address, opts blockchain.TokenAccountsOptions) ([]*blockchain.TokenAccountInfo, error) {
	ret := _mock.Called(ctx, ownerAddress, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenAccountsByOwner")
	}

	var r0 []*blockchain.TokenAccountInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, blockchain.Address, blockchain.TokenAccountsOptions) ([]*blockchain.TokenAccountInfo, error)); ok {
		return returnFunc(ctx, ownerAddress, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, blockchain.Address, blockchain.TokenAccountsOptions) []*blockchain.TokenAccountInfo); ok {
		r0 = returnFunc(ctx, ownerAddress, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*blockchain.TokenAccountInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, blockchain.Address, blockchain.TokenAccountsOptions) error); ok {
		r1 = returnFunc(ctx, ownerAddress, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenericClientAPI_GetTokenAccountsByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenAccountsByOwner'
type MockGenericClientAPI_GetTokenAccountsByOwner_Call struct {
	*mock.Call
}

// GetTokenAccountsByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerAddress blockchain.Address
//   - opts blockchain.TokenAccountsOptions
func (_e *MockGenericClientAPI_Expecter) GetTokenAccountsByOwner(ctx interface{}, ownerAddress interface{}, opts interface{}) *MockGenericClientAPI_GetTokenAccountsByOwner_Call {
	return &MockGenericClientAPI_GetTokenAccountsByOwner_Call{Call: _e.mock.On("GetTokenAccountsByOwner", ctx, ownerAddress, opts)}
}

func (_c *MockGenericClientAPI_GetTokenAccountsByOwner_Call) Run(run func(ctx context.Context, ownerAddress blockchain.Address, opts blockchain.TokenAccountsOptions)) *MockGenericClientAPI_GetTokenAccountsByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 blockchain.Address
		if args[1] != nil {
			arg1 = args[1].(blockchain.Address)
		}
		var arg2 blockchain.TokenAccountsOptions
		if args[2] != nil {
			arg2 = args[2].(blockchain.TokenAccountsOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGenericClientAPI_GetTokenAccountsByOwner_Call) Return(tokenAccountInfos []*blockchain.TokenAccountInfo, err error) *MockGenericClientAPI_GetTokenAccountsByOwner_Call {
	_c.Call.Return(tokenAccountInfos, err)
	return _c
}

func (_c *MockGenericClientAPI_GetTokenAccountsByOwner_Call) RunAndReturn(run func(ctx context.Context, ownerAddress blockchain.Address, opts blockchain.TokenAccountsOptions) ([]*blockchain.TokenAccountInfo, error)) *MockGenericClientAPI_GetTokenAccountsByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenBalance provides a mock function for the type MockGenericClientAPI
func (_mock *MockGenericClientAPI) GetTokenBalance(ctx context.Context, ownerAddress blockchain.Address, tokenMintAddress blockchain.Address, commitment string) (*blockchain.Balance, error) {
	ret := _mock.Called(ctx, ownerAddress, tokenMintAddress, commitment)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenBalance")
	}

	var r0 *blockchain.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, blockchain.Address, blockchain.Address, string) (*blockchain.Balance, error)); ok {
		return returnFunc(ctx, ownerAddress, tokenMintAddress, commitment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, blockchain.Address, blockchain.Address, string) *blockchain.Balance); ok {
		r0 = returnFunc(ctx, ownerAddress, tokenMintAddress, commitment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*blockchain.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, blockchain.Address, blockchain.Address, string) error); ok {
		r1 = returnFunc(ctx, ownerAddress, tokenMintAddress, commitment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenericClientAPI_GetTokenBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenBalance'
type MockGenericClientAPI_GetTokenBalance_Call struct {
	*mock.Call
}

// GetTokenBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerAddress blockchain.Address
//   - tokenMintAddress blockchain.Address
//   - commitment string
func (_e *MockGenericClientAPI_Expecter) GetTokenBalance(ctx interface{}, ownerAddress interface{}, tokenMintAddress interface{}, commitment interface{}) *MockGenericClientAPI_GetTokenBalance_Call {
	return &MockGenericClientAPI_GetTokenBalance_Call{Call: _e.mock.On("GetTokenBalance", ctx, ownerAddress, tokenMintAddress, commitment)}
}

func (_c *MockGenericClientAPI_GetTokenBalance_Call) Run(run func(ctx context.Context, ownerAddress blockchain.Address, tokenMintAddress blockchain.Address, commitment string)) *MockGenericClientAPI_GetTokenBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 blockchain.Address
		if args[1] != nil {
			arg1 = args[1].(blockchain.Address)
		}
		var arg2 blockchain.Address
		if args[2] != nil {
			arg2 = args[2].(blockchain.Address)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGenericClientAPI_GetTokenBalance_Call) Return(balance *blockchain.Balance, err error) *MockGenericClientAPI_GetTokenBalance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockGenericClientAPI_GetTokenBalance_Call) RunAndReturn(run func(ctx context.Context, ownerAddress blockchain.Address, tokenMintAddress blockchain.Address, commitment string) (*blockchain.Balance, error)) *MockGenericClientAPI_GetTokenBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenMetadata provides a mock function for the type MockGenericClientAPI
func (_mock *MockGenericClientAPI) GetTokenMetadata(ctx context.Context, mintAddress blockchain.Address) (*blockchain.TokenMetadata, error) {
	ret := _mock.Called(ctx, mintAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenMetadata")
	}

	var r0 *blockchain.TokenMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, blockchain.Address) (*blockchain.TokenMetadata, error)); ok {
		return returnFunc(ctx, mintAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, blockchain.Address) *blockchain.TokenMetadata); ok {
		r0 = returnFunc(ctx, mintAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*blockchain.TokenMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, blockchain.Address) error); ok {
		r1 = returnFunc(ctx, mintAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenericClientAPI_GetTokenMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenMetadata'
type MockGenericClientAPI_GetTokenMetadata_Call struct {
	*mock.Call
}

// GetTokenMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - mintAddress blockchain.Address
func (_e *MockGenericClientAPI_Expecter) GetTokenMetadata(ctx interface{}, mintAddress interface{}) *MockGenericClientAPI_GetTokenMetadata_Call {
	return &MockGenericClientAPI_GetTokenMetadata_Call{Call: _e.mock.On("GetTokenMetadata", ctx, mintAddress)}
}

func (_c *MockGenericClientAPI_GetTokenMetadata_Call) Run(run func(ctx context.Context, mintAddress blockchain.Address)) *MockGenericClientAPI_GetTokenMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 blockchain.Address
		if args[1] != nil {
			arg1 = args[1].(blockchain.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenericClientAPI_GetTokenMetadata_Call) Return(tokenMetadata *blockchain.TokenMetadata, err error) *MockGenericClientAPI_GetTokenMetadata_Call {
	_c.Call.Return(tokenMetadata, err)
	return _c
}

func (_c *MockGenericClientAPI_GetTokenMetadata_Call) RunAndReturn(run func(ctx context.Context, mintAddress blockchain.Address) (*blockchain.TokenMetadata, error)) *MockGenericClientAPI_GetTokenMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionStatus provides a mock function for the type MockGenericClientAPI
func (_mock *MockGenericClientAPI) GetTransactionStatus(ctx context.Context, signature blockchain.Signature) (*blockchain.TransactionStatus, error) {
	ret := _mock.Called(ctx, signature)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionStatus")
	}

	var r0 *blockchain.TransactionStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, blockchain.Signature) (*blockchain.TransactionStatus, error)); ok {
		return returnFunc(ctx, signature)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, blockchain.Signature) *blockchain.TransactionStatus); ok {
		r0 = returnFunc(ctx, signature)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*blockchain.TransactionStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, blockchain.Signature) error); ok {
		r1 = returnFunc(ctx, signature)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenericClientAPI_GetTransactionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionStatus'
type MockGenericClientAPI_GetTransactionStatus_Call struct {
	*mock.Call
}

// GetTransactionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - signature blockchain.Signature
func (_e *MockGenericClientAPI_Expecter) GetTransactionStatus(ctx interface{}, signature interface{}) *MockGenericClientAPI_GetTransactionStatus_Call {
	return &MockGenericClientAPI_GetTransactionStatus_Call{Call: _e.mock.On("GetTransactionStatus", ctx, signature)}
}

func (_c *MockGenericClientAPI_GetTransactionStatus_Call) Run(run func(ctx context.Context, signature blockchain.Signature)) *MockGenericClientAPI_GetTransactionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 blockchain.Signature
		if args[1] != nil {
			arg1 = args[1].(blockchain.Signature)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenericClientAPI_GetTransactionStatus_Call) Return(transactionStatus *blockchain.TransactionStatus, err error) *MockGenericClientAPI_GetTransactionStatus_Call {
	_c.Call.Return(transactionStatus, err)
	return _c
}

func (_c *MockGenericClientAPI_GetTransactionStatus_Call) RunAndReturn(run func(ctx context.Context, signature blockchain.Signature) (*blockchain.TransactionStatus, error)) *MockGenericClientAPI_GetTransactionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SendRawTransaction provides a mock function for the type MockGenericClientAPI
func (_mock *MockGenericClientAPI) SendRawTransaction(ctx context.Context, rawTx []byte, opts blockchain.TransactionOptions) (blockchain.Signature, error) {
	ret := _mock.Called(ctx, rawTx, opts)

	if len(ret) == 0 {
		panic("no return value specified for SendRawTransaction")
	}

	var r0 blockchain.Signature
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, blockchain.TransactionOptions) (blockchain.Signature, error)); ok {
		return returnFunc(ctx, rawTx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, blockchain.TransactionOptions) blockchain.Signature); ok {
		r0 = returnFunc(ctx, rawTx, opts)
	} else {
		r0 = ret.Get(0).(blockchain.Signature)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, blockchain.TransactionOptions) error); ok {
		r1 = returnFunc(ctx, rawTx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenericClientAPI_SendRawTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRawTransaction'
type MockGenericClientAPI_SendRawTransaction_Call struct {
	*mock.Call
}

// SendRawTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - rawTx []byte
//   - opts blockchain.TransactionOptions
func (_e *MockGenericClientAPI_Expecter) SendRawTransaction(ctx interface{}, rawTx interface{}, opts interface{}) *MockGenericClientAPI_SendRawTransaction_Call {
	return &MockGenericClientAPI_SendRawTransaction_Call{Call: _e.mock.On("SendRawTransaction", ctx, rawTx, opts)}
}

func (_c *MockGenericClientAPI_SendRawTransaction_Call) Run(run func(ctx context.Context, rawTx []byte, opts blockchain.TransactionOptions)) *MockGenericClientAPI_SendRawTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 blockchain.TransactionOptions
		if args[2] != nil {
			arg2 = args[2].(blockchain.TransactionOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGenericClientAPI_SendRawTransaction_Call) Return(signature blockchain.Signature, err error) *MockGenericClientAPI_SendRawTransaction_Call {
	_c.Call.Return(signature, err)
	return _c
}

func (_c *MockGenericClientAPI_SendRawTransaction_Call) RunAndReturn(run func(ctx context.Context, rawTx []byte, opts blockchain.TransactionOptions) (blockchain.Signature, error)) *MockGenericClientAPI_SendRawTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// SendTransaction provides a mock function for the type MockGenericClientAPI
func (_mock *MockGenericClientAPI) SendTransaction(ctx context.Context, tx *blockchain.Transaction, opts blockchain.TransactionOptions) (blockchain.Signature, error) {
	ret := _mock.Called(ctx, tx, opts)

	if len(ret) == 0 {
		panic("no return value specified for SendTransaction")
	}

	var r0 blockchain.Signature
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *blockchain.Transaction, blockchain.TransactionOptions) (blockchain.Signature, error)); ok {
		return returnFunc(ctx, tx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *blockchain.Transaction, blockchain.TransactionOptions) blockchain.Signature); ok {
		r0 = returnFunc(ctx, tx, opts)
	} else {
		r0 = ret.Get(0).(blockchain.Signature)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *blockchain.Transaction, blockchain.TransactionOptions) error); ok {
		r1 = returnFunc(ctx, tx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenericClientAPI_SendTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTransaction'
type MockGenericClientAPI_SendTransaction_Call struct {
	*mock.Call
}

// SendTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *blockchain.Transaction
//   - opts blockchain.TransactionOptions
func (_e *MockGenericClientAPI_Expecter) SendTransaction(ctx interface{}, tx interface{}, opts interface{}) *MockGenericClientAPI_SendTransaction_Call {
	return &MockGenericClientAPI_SendTransaction_Call{Call: _e.mock.On("SendTransaction", ctx, tx, opts)}
}

func (_c *MockGenericClientAPI_SendTransaction_Call) Run(run func(ctx context.Context, tx *blockchain.Transaction, opts blockchain.TransactionOptions)) *MockGenericClientAPI_SendTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *blockchain.Transaction
		if args[1] != nil {
			arg1 = args[1].(*blockchain.Transaction)
		}
		var arg2 blockchain.TransactionOptions
		if args[2] != nil {
			arg2 = args[2].(blockchain.TransactionOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGenericClientAPI_SendTransaction_Call) Return(signature blockchain.Signature, err error) *MockGenericClientAPI_SendTransaction_Call {
	_c.Call.Return(signature, err)
	return _c
}

func (_c *MockGenericClientAPI_SendTransaction_Call) RunAndReturn(run func(ctx context.Context, tx *blockchain.Transaction, opts blockchain.TransactionOptions) (blockchain.Signature, error)) *MockGenericClientAPI_SendTransaction_Call {
	_c.Call.Return(run)
	return _c
}
