// Code generated by mockery v2.53.4. DO NOT EDIT.

package clientsmocks

import mock "github.com/stretchr/testify/mock"

// MockAPICallTracker is an autogenerated mock type for the APICallTracker type
type MockAPICallTracker struct {
	mock.Mock
}

type MockAPICallTracker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPICallTracker) EXPECT() *MockAPICallTracker_Expecter {
	return &MockAPICallTracker_Expecter{mock: &_m.Mock}
}

// GetStats provides a mock function with no fields
func (_m *MockAPICallTracker) GetStats() map[string]map[string]int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 map[string]map[string]int
	if rf, ok := ret.Get(0).(func() map[string]map[string]int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]map[string]int)
		}
	}

	return r0
}

// MockAPICallTracker_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockAPICallTracker_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
func (_e *MockAPICallTracker_Expecter) GetStats() *MockAPICallTracker_GetStats_Call {
	return &MockAPICallTracker_GetStats_Call{Call: _e.mock.On("GetStats")}
}

func (_c *MockAPICallTracker_GetStats_Call) Run(run func()) *MockAPICallTracker_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPICallTracker_GetStats_Call) Return(_a0 map[string]map[string]int) *MockAPICallTracker_GetStats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPICallTracker_GetStats_Call) RunAndReturn(run func() map[string]map[string]int) *MockAPICallTracker_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// TrackCall provides a mock function with given fields: serviceName, endpointName
func (_m *MockAPICallTracker) TrackCall(serviceName string, endpointName string) {
	_m.Called(serviceName, endpointName)
}

// MockAPICallTracker_TrackCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackCall'
type MockAPICallTracker_TrackCall_Call struct {
	*mock.Call
}

// TrackCall is a helper method to define mock.On call
//   - serviceName string
//   - endpointName string
func (_e *MockAPICallTracker_Expecter) TrackCall(serviceName interface{}, endpointName interface{}) *MockAPICallTracker_TrackCall_Call {
	return &MockAPICallTracker_TrackCall_Call{Call: _e.mock.On("TrackCall", serviceName, endpointName)}
}

func (_c *MockAPICallTracker_TrackCall_Call) Run(run func(serviceName string, endpointName string)) *MockAPICallTracker_TrackCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockAPICallTracker_TrackCall_Call) Return() *MockAPICallTracker_TrackCall_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAPICallTracker_TrackCall_Call) RunAndReturn(run func(string, string)) *MockAPICallTracker_TrackCall_Call {
	_c.Run(run)
	return _c
}

// NewMockAPICallTracker creates a new instance of MockAPICallTracker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPICallTracker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPICallTracker {
	mock := &MockAPICallTracker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
