all: false
dir: '{{.InterfaceDir}}/mocks'
filename: '{{.InterfaceName}}.go'
force-file-write: true
formatter: goimports
log-level: info
structname: 'Mock{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}mocks'
recursive: false
require-template-schema-exists: false
template: testify

packages:
  github.com/nicolas-martin/dankfolio/backend/internal/clients/birdeye:
    interfaces:
      ClientAPI:
  github.com/nicolas-martin/dankfolio/backend/internal/clients/jupiter:
    interfaces:
      ClientAPI:
  github.com/nicolas-martin/dankfolio/backend/internal/clients/offchain:
    interfaces:
      ClientAPI:
  github.com/nicolas-martin/dankfolio/backend/internal/clients/solana:
    interfaces:
      ClientAPI:
      SolanaRPCClientAPI:
  github.com/nicolas-martin/dankfolio/backend/internal/db:
    interfaces:
      Repository:
      Store:
      Entity:
  github.com/nicolas-martin/dankfolio/backend/internal/service/coin:
    interfaces:
      CoinServiceAPI:
  github.com/nicolas-martin/dankfolio/backend/internal/service/price:
    interfaces:
      PriceServiceAPI:
