_anchors:
  common-config: &common-config
    dir: "{{.InterfaceDir}}/mocks"
    filename: "{{.InterfaceName}}.go"
    pkgname: "{{.SrcPackageName}}mocks" # Used SrcPackageName
    # template-data:
    #   unroll-variadic: true

packages:
  github.com/nicolas-martin/dankfolio/backend/internal/clients/birdeye:
    config:
      <<: *common-config
    interfaces:
      ClientAPI: # From client.go
  github.com/nicolas-martin/dankfolio/backend/internal/clients/jupiter:
    config:
      <<: *common-config
    interfaces:
      ClientAPI:
  github.com/nicolas-martin/dankfolio/backend/internal/clients/offchain:
    config:
      <<: *common-config
    interfaces:
      ClientAPI:
  github.com/nicolas-martin/dankfolio/backend/internal/clients/solana:
    config:
      <<: *common-config
    interfaces:
      ClientAPI: # From interfaces.go
      SolanaRPCClientAPI: # From rpc_client_api.go
  github.com/nicolas-martin/dankfolio/backend/internal/db:
    config:
      <<: *common-config
    interfaces:
      Repository:
      Store:
  github.com/nicolas-martin/dankfolio/backend/internal/service/coin:
    config:
      <<: *common-config
    interfaces:
      CoinServiceAPI: # From api.go
  github.com/nicolas-martin/dankfolio/backend/internal/service/price:
    config:
      <<: *common-config
    interfaces:
      PriceServiceAPI: # From api.go
