packages:
  github.com/nicolas-martin/dankfolio/backend/internal/clients:
    interfaces:
      APICallTracker:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          outpkg: "{{.PackageName}}mocks"
  github.com/nicolas-martin/dankfolio/backend/internal/clients/birdeye:
    interfaces:
      ClientAPI: # From client.go
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "{{.InterfaceName}}.go"
          outpkg: "{{.PackageName}}mocks" # Used .PackageName instead of .SrcPackageName and lowercased "mocks"
          # template-data:
          #   unroll-variadic: true
  github.com/nicolas-martin/dankfolio/backend/internal/clients/jupiter:
    interfaces:
      ClientAPI:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "{{.InterfaceName}}.go"
          outpkg: "{{.PackageName}}mocks"
          # template-data:
          #   unroll-variadic: true
  github.com/nicolas-martin/dankfolio/backend/internal/clients/offchain:
    interfaces:
      ClientAPI:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "{{.InterfaceName}}.go"
          outpkg: "{{.PackageName}}mocks"
          # template-data:
          #   unroll-variadic: true
  github.com/nicolas-martin/dankfolio/backend/internal/clients/solana:
    interfaces:
      ClientAPI: # From interfaces.go
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "{{.InterfaceName}}.go"
          outpkg: "{{.PackageName}}mocks"
          # template-data:
          #   unroll-variadic: true
      SolanaRPCClientAPI: # From rpc_client_api.go
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "{{.InterfaceName}}.go"
          outpkg: "{{.PackageName}}mocks"
          # template-data:
          #   unroll-variadic: true
  github.com/nicolas-martin/dankfolio/backend/internal/db:
    interfaces:
      Repository:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "{{.InterfaceName}}.go"
          outpkg: "{{.PackageName}}mocks"
          # template-data:
          #   unroll-variadic: true
      Store:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "{{.InterfaceName}}.go"
          outpkg: "{{.PackageName}}mocks"
          # template-data:
          #   unroll-variadic: true
      Entity:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          outpkg: "{{.PackageName}}mocks"
  github.com/nicolas-martin/dankfolio/backend/internal/service/coin:
    interfaces:
      CoinServiceAPI: # From api.go
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "{{.InterfaceName}}.go"
          outpkg: "{{.PackageName}}mocks"
          # template-data:
          #   unroll-variadic: true
  github.com/nicolas-martin/dankfolio/backend/internal/service/price:
    interfaces:
      PriceServiceAPI: # From api.go
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "{{.InterfaceName}}.go"
          outpkg: "{{.PackageName}}mocks"
          # template-data:
          #   unroll-variadic: true
