package coin

import (
	"time"

	"github.com/nicolas-martin/dankfolio/backend/internal/model"
)

const (
	// CacheExpiration is the duration for which cached data is valid
	CacheExpiration = 5 * time.Minute
	// TrendingDataTTL is the maximum age for the scraped trending data file
	TrendingDataTTL = 24 * time.Hour
	// defaultTrendingTokenPath is the default location if not overridden in config
	defaultTrendingTokenPath = "backend/data/trending_solana_tokens_enriched.json"
	// Initial load timeout
	initialLoadTimeout = 3 * time.Minute // Max time for initial load/scrape
)

// Config holds the configuration for the coin service
type Config struct {
	BirdEyeBaseURL    string
	BirdEyeAPIKey     string
	TrendingTokenPath string // Path to the JSON file generated by the scraper
	CoinGeckoAPIKey   string // Uncomment when needed
	SolanaRPCEndpoint string // Add Solana RPC endpoint needed for enrichment client
}

// --- Structs matching the scraper's NEW JSON output (Enriched Data) ---

// EnrichedFileOutput matches the top-level structure of the NEW trending_solana_tokens.json
type EnrichedFileOutput struct {
	ScrapeTimestamp time.Time    `json:"scrapeTimestamp"`
	Coins           []model.Coin `json:"coins"` // Contains fully enriched Coin models
}

// --- End scraper JSON structs ---
// TokenInfo represents a token from the Raydium API
type TokenInfo struct {
	Symbol   string `json:"symbol"`
	Name     string `json:"name"`
	Mint     string `json:"mint"` // This is the ID we'll use
	Decimals int    `json:"decimals"`
	LogoURI  string `json:"logoURI"`
}

// RaydiumPool represents a liquidity pool from the Raydium API
type RaydiumPool struct {
	ID            string `json:"id"`
	BaseMint      string `json:"baseMint"`
	QuoteMint     string `json:"quoteMint"`
	BaseDecimals  int    `json:"baseDecimals"`
	QuoteDecimals int    `json:"quoteDecimals"`
	MarketID      string `json:"marketId"`
}

// TokenPoolInfo combines token information with its pools
type TokenPoolInfo struct {
	Token TokenInfo     `json:"token"`
	Pools []RaydiumPool `json:"pools"`
}

// TokenPoolInfoList represents the JSON structure of our token data file
type TokenPoolInfoList struct {
	Tokens []TokenPoolInfo `json:"tokens"`
}

// RaydiumTokenResponse represents the token list API response
type RaydiumTokenResponse struct {
	Official   []TokenInfo `json:"official"`
	Unofficial []TokenInfo `json:"unOfficial"`
}

// RaydiumPoolsResponse represents the pools API response
type RaydiumPoolsResponse struct {
	Name       string        `json:"name"`
	Official   []RaydiumPool `json:"official"`
	Unofficial []RaydiumPool `json:"unOfficial"`
}

// TokenList represents the structure of trimmed_mainnet.json
type TokenList struct {
	Tokens []struct {
		Token struct {
			Symbol   string `json:"symbol"`
			Name     string `json:"name"`
			Mint     string `json:"mint"`
			Decimals int    `json:"decimals"`
		} `json:"token"`
		Pools []struct {
			ID string `json:"id"`
		} `json:"pools"`
	} `json:"tokens"`
}

// CoinGeckoMetadata represents the raw response from CoinGecko API
type CoinGeckoMetadata struct {
	ID     string `json:"id"`
	Symbol string `json:"symbol"`
	Name   string `json:"name"`
	Links  struct {
		Homepage                  []string `json:"homepage"`
		TwitterScreenName         string   `json:"twitter_screen_name"`
		TelegramChannelIdentifier string   `json:"telegram_channel_identifier"`
	} `json:"links"`
	Image struct {
		Large string `json:"large"`
	} `json:"image"`
	LastUpdated string `json:"last_updated"`
}
