// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package coinmocks

import (
	"context"

	"github.com/nicolas-martin/dankfolio/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCoinServiceAPI creates a new instance of MockCoinServiceAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCoinServiceAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCoinServiceAPI {
	mock := &MockCoinServiceAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCoinServiceAPI is an autogenerated mock type for the CoinServiceAPI type
type MockCoinServiceAPI struct {
	mock.Mock
}

type MockCoinServiceAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCoinServiceAPI) EXPECT() *MockCoinServiceAPI_Expecter {
	return &MockCoinServiceAPI_Expecter{mock: &_m.Mock}
}

// GetCoinByAddress provides a mock function for the type MockCoinServiceAPI
func (_mock *MockCoinServiceAPI) GetCoinByAddress(ctx context.Context, address string) (*model.Coin, error) {
	ret := _mock.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetCoinByAddress")
	}

	var r0 *model.Coin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Coin, error)); ok {
		return returnFunc(ctx, address)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Coin); ok {
		r0 = returnFunc(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Coin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, address)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCoinServiceAPI_GetCoinByAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoinByAddress'
type MockCoinServiceAPI_GetCoinByAddress_Call struct {
	*mock.Call
}

// GetCoinByAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
func (_e *MockCoinServiceAPI_Expecter) GetCoinByAddress(ctx interface{}, address interface{}) *MockCoinServiceAPI_GetCoinByAddress_Call {
	return &MockCoinServiceAPI_GetCoinByAddress_Call{Call: _e.mock.On("GetCoinByAddress", ctx, address)}
}

func (_c *MockCoinServiceAPI_GetCoinByAddress_Call) Run(run func(ctx context.Context, address string)) *MockCoinServiceAPI_GetCoinByAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCoinServiceAPI_GetCoinByAddress_Call) Return(coin *model.Coin, err error) *MockCoinServiceAPI_GetCoinByAddress_Call {
	_c.Call.Return(coin, err)
	return _c
}

func (_c *MockCoinServiceAPI_GetCoinByAddress_Call) RunAndReturn(run func(ctx context.Context, address string) (*model.Coin, error)) *MockCoinServiceAPI_GetCoinByAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoinByID provides a mock function for the type MockCoinServiceAPI
func (_mock *MockCoinServiceAPI) GetCoinByID(ctx context.Context, id string) (*model.Coin, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCoinByID")
	}

	var r0 *model.Coin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Coin, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Coin); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Coin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCoinServiceAPI_GetCoinByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoinByID'
type MockCoinServiceAPI_GetCoinByID_Call struct {
	*mock.Call
}

// GetCoinByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCoinServiceAPI_Expecter) GetCoinByID(ctx interface{}, id interface{}) *MockCoinServiceAPI_GetCoinByID_Call {
	return &MockCoinServiceAPI_GetCoinByID_Call{Call: _e.mock.On("GetCoinByID", ctx, id)}
}

func (_c *MockCoinServiceAPI_GetCoinByID_Call) Run(run func(ctx context.Context, id string)) *MockCoinServiceAPI_GetCoinByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCoinServiceAPI_GetCoinByID_Call) Return(coin *model.Coin, err error) *MockCoinServiceAPI_GetCoinByID_Call {
	_c.Call.Return(coin, err)
	return _c
}

func (_c *MockCoinServiceAPI_GetCoinByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Coin, error)) *MockCoinServiceAPI_GetCoinByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoinsByAddresses provides a mock function for the type MockCoinServiceAPI
func (_mock *MockCoinServiceAPI) GetCoinsByAddresses(ctx context.Context, addresses []string, forceRefresh bool) ([]model.Coin, error) {
	ret := _mock.Called(ctx, addresses, forceRefresh)

	if len(ret) == 0 {
		panic("no return value specified for GetCoinsByAddresses")
	}

	var r0 []model.Coin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, bool) ([]model.Coin, error)); ok {
		return returnFunc(ctx, addresses, forceRefresh)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, bool) []model.Coin); ok {
		r0 = returnFunc(ctx, addresses, forceRefresh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Coin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, bool) error); ok {
		r1 = returnFunc(ctx, addresses, forceRefresh)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCoinServiceAPI_GetCoinsByAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoinsByAddresses'
type MockCoinServiceAPI_GetCoinsByAddresses_Call struct {
	*mock.Call
}

// GetCoinsByAddresses is a helper method to define mock.On call
//   - ctx context.Context
//   - addresses []string
//   - forceRefresh bool
func (_e *MockCoinServiceAPI_Expecter) GetCoinsByAddresses(ctx interface{}, addresses interface{}, forceRefresh interface{}) *MockCoinServiceAPI_GetCoinsByAddresses_Call {
	return &MockCoinServiceAPI_GetCoinsByAddresses_Call{Call: _e.mock.On("GetCoinsByAddresses", ctx, addresses, forceRefresh)}
}

func (_c *MockCoinServiceAPI_GetCoinsByAddresses_Call) Run(run func(ctx context.Context, addresses []string, forceRefresh bool)) *MockCoinServiceAPI_GetCoinsByAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCoinServiceAPI_GetCoinsByAddresses_Call) Return(coins []model.Coin, err error) *MockCoinServiceAPI_GetCoinsByAddresses_Call {
	_c.Call.Return(coins, err)
	return _c
}

func (_c *MockCoinServiceAPI_GetCoinsByAddresses_Call) RunAndReturn(run func(ctx context.Context, addresses []string, forceRefresh bool) ([]model.Coin, error)) *MockCoinServiceAPI_GetCoinsByAddresses_Call {
	_c.Call.Return(run)
	return _c
}
