// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nicolas-martin/dankfolio/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// CoinServiceAPI is an autogenerated mock type for the CoinServiceAPI type
type CoinServiceAPI struct {
	mock.Mock
}

// GetCoinByID provides a mock function with given fields: ctx, id
func (_m *CoinServiceAPI) GetCoinByID(ctx context.Context, id string) (*model.Coin, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCoinByID")
	}

	var r0 *model.Coin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Coin, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Coin); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Coin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCoinServiceAPI creates a new instance of CoinServiceAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoinServiceAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoinServiceAPI {
	mock := &CoinServiceAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
