// Code generated by mockery v2.53.4. DO NOT EDIT.

package offchainmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockClientAPI is an autogenerated mock type for the ClientAPI type
type MockClientAPI struct {
	mock.Mock
}

type MockClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientAPI) EXPECT() *MockClientAPI_Expecter {
	return &MockClientAPI_Expecter{mock: &_m.Mock}
}

// FetchMetadata provides a mock function with given fields: uri
func (_m *MockClientAPI) FetchMetadata(uri string) (map[string]interface{}, error) {
	ret := _m.Called(uri)

	if len(ret) == 0 {
		panic("no return value specified for FetchMetadata")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (map[string]interface{}, error)); ok {
		return rf(uri)
	}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uri)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_FetchMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchMetadata'
type MockClientAPI_FetchMetadata_Call struct {
	*mock.Call
}

// FetchMetadata is a helper method to define mock.On call
//   - uri string
func (_e *MockClientAPI_Expecter) FetchMetadata(uri interface{}) *MockClientAPI_FetchMetadata_Call {
	return &MockClientAPI_FetchMetadata_Call{Call: _e.mock.On("FetchMetadata", uri)}
}

func (_c *MockClientAPI_FetchMetadata_Call) Run(run func(uri string)) *MockClientAPI_FetchMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClientAPI_FetchMetadata_Call) Return(_a0 map[string]interface{}, _a1 error) *MockClientAPI_FetchMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_FetchMetadata_Call) RunAndReturn(run func(string) (map[string]interface{}, error)) *MockClientAPI_FetchMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// FetchRawData provides a mock function with given fields: ctx, uri
func (_m *MockClientAPI) FetchRawData(ctx context.Context, uri string) ([]byte, string, error) {
	ret := _m.Called(ctx, uri)

	if len(ret) == 0 {
		panic("no return value specified for FetchRawData")
	}

	var r0 []byte
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, string, error)); ok {
		return rf(ctx, uri)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, uri)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, uri)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClientAPI_FetchRawData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRawData'
type MockClientAPI_FetchRawData_Call struct {
	*mock.Call
}

// FetchRawData is a helper method to define mock.On call
//   - ctx context.Context
//   - uri string
func (_e *MockClientAPI_Expecter) FetchRawData(ctx interface{}, uri interface{}) *MockClientAPI_FetchRawData_Call {
	return &MockClientAPI_FetchRawData_Call{Call: _e.mock.On("FetchRawData", ctx, uri)}
}

func (_c *MockClientAPI_FetchRawData_Call) Run(run func(ctx context.Context, uri string)) *MockClientAPI_FetchRawData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClientAPI_FetchRawData_Call) Return(data []byte, contentType string, err error) *MockClientAPI_FetchRawData_Call {
	_c.Call.Return(data, contentType, err)
	return _c
}

func (_c *MockClientAPI_FetchRawData_Call) RunAndReturn(run func(context.Context, string) ([]byte, string, error)) *MockClientAPI_FetchRawData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientAPI creates a new instance of MockClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientAPI {
	mock := &MockClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
