// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package offchainMocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientAPI creates a new instance of MockClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientAPI {
	mock := &MockClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientAPI is an autogenerated mock type for the ClientAPI type
type MockClientAPI struct {
	mock.Mock
}

type MockClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientAPI) EXPECT() *MockClientAPI_Expecter {
	return &MockClientAPI_Expecter{mock: &_m.Mock}
}

// FetchMetadata provides a mock function for the type MockClientAPI
func (_mock *MockClientAPI) FetchMetadata(uri string) (map[string]interface{}, error) {
	ret := _mock.Called(uri)

	if len(ret) == 0 {
		panic("no return value specified for FetchMetadata")
	}

	var r0 map[string]interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (map[string]interface{}, error)); ok {
		return returnFunc(uri)
	}
	if returnFunc, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = returnFunc(uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(uri)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAPI_FetchMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchMetadata'
type MockClientAPI_FetchMetadata_Call struct {
	*mock.Call
}

// FetchMetadata is a helper method to define mock.On call
//   - uri
func (_e *MockClientAPI_Expecter) FetchMetadata(uri interface{}) *MockClientAPI_FetchMetadata_Call {
	return &MockClientAPI_FetchMetadata_Call{Call: _e.mock.On("FetchMetadata", uri)}
}

func (_c *MockClientAPI_FetchMetadata_Call) Run(run func(uri string)) *MockClientAPI_FetchMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClientAPI_FetchMetadata_Call) Return(stringToIfaceVal map[string]interface{}, err error) *MockClientAPI_FetchMetadata_Call {
	_c.Call.Return(stringToIfaceVal, err)
	return _c
}

func (_c *MockClientAPI_FetchMetadata_Call) RunAndReturn(run func(uri string) (map[string]interface{}, error)) *MockClientAPI_FetchMetadata_Call {
	_c.Call.Return(run)
	return _c
}
