// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nicolas-martin/dankfolio/backend/internal/model"
	mock "github.com/stretchr/testify/mock"

	rpc "github.com/gagliardetto/solana-go/rpc"

	solana "github.com/gagliardetto/solana-go"

	token_metadata "github.com/blocto/solana-go-sdk/program/metaplex/token_metadata"
)

// ClientAPI is an autogenerated mock type for the ClientAPI type
type ClientAPI struct {
	mock.Mock
}

// ExecuteSignedTransaction provides a mock function with given fields: ctx, signedTx
func (_m *ClientAPI) ExecuteSignedTransaction(ctx context.Context, signedTx string) (solana.Signature, error) {
	ret := _m.Called(ctx, signedTx)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteSignedTransaction")
	}

	var r0 solana.Signature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (solana.Signature, error)); ok {
		return rf(ctx, signedTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) solana.Signature); ok {
		r0 = rf(ctx, signedTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(solana.Signature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, signedTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecuteTrade provides a mock function with given fields: ctx, trade, signedTx
func (_m *ClientAPI) ExecuteTrade(ctx context.Context, trade *model.Trade, signedTx string) error {
	ret := _m.Called(ctx, trade, signedTx)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTrade")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Trade, string) error); ok {
		r0 = rf(ctx, trade, signedTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMetadataAccount provides a mock function with given fields: ctx, mint
func (_m *ClientAPI) GetMetadataAccount(ctx context.Context, mint string) (*token_metadata.Metadata, error) {
	ret := _m.Called(ctx, mint)

	if len(ret) == 0 {
		panic("no return value specified for GetMetadataAccount")
	}

	var r0 *token_metadata.Metadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*token_metadata.Metadata, error)); ok {
		return rf(ctx, mint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *token_metadata.Metadata); ok {
		r0 = rf(ctx, mint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token_metadata.Metadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, mint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRpcConnection provides a mock function with no fields
func (_m *ClientAPI) GetRpcConnection() *rpc.Client {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRpcConnection")
	}

	var r0 *rpc.Client
	if rf, ok := ret.Get(0).(func() *rpc.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.Client)
		}
	}

	return r0
}

// NewClientAPI creates a new instance of ClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientAPI {
	mock := &ClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
