// Code generated by mockery v2.53.4. DO NOT EDIT.

package solanamocks

import (
	context "context"

	model "github.com/nicolas-martin/dankfolio/backend/internal/model"
	mock "github.com/stretchr/testify/mock"

	solana "github.com/gagliardetto/solana-go"

	token_metadata "github.com/blocto/solana-go-sdk/program/metaplex/token_metadata"
)

// MockClientAPI is an autogenerated mock type for the ClientAPI type
type MockClientAPI struct {
	mock.Mock
}

type MockClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientAPI) EXPECT() *MockClientAPI_Expecter {
	return &MockClientAPI_Expecter{mock: &_m.Mock}
}

// ExecuteSignedTransaction provides a mock function with given fields: ctx, signedTx
func (_m *MockClientAPI) ExecuteSignedTransaction(ctx context.Context, signedTx string) (solana.Signature, error) {
	ret := _m.Called(ctx, signedTx)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteSignedTransaction")
	}

	var r0 solana.Signature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (solana.Signature, error)); ok {
		return rf(ctx, signedTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) solana.Signature); ok {
		r0 = rf(ctx, signedTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(solana.Signature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, signedTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_ExecuteSignedTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteSignedTransaction'
type MockClientAPI_ExecuteSignedTransaction_Call struct {
	*mock.Call
}

// ExecuteSignedTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - signedTx string
func (_e *MockClientAPI_Expecter) ExecuteSignedTransaction(ctx interface{}, signedTx interface{}) *MockClientAPI_ExecuteSignedTransaction_Call {
	return &MockClientAPI_ExecuteSignedTransaction_Call{Call: _e.mock.On("ExecuteSignedTransaction", ctx, signedTx)}
}

func (_c *MockClientAPI_ExecuteSignedTransaction_Call) Run(run func(ctx context.Context, signedTx string)) *MockClientAPI_ExecuteSignedTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClientAPI_ExecuteSignedTransaction_Call) Return(_a0 solana.Signature, _a1 error) *MockClientAPI_ExecuteSignedTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_ExecuteSignedTransaction_Call) RunAndReturn(run func(context.Context, string) (solana.Signature, error)) *MockClientAPI_ExecuteSignedTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteTrade provides a mock function with given fields: ctx, trade, signedTx
func (_m *MockClientAPI) ExecuteTrade(ctx context.Context, trade *model.Trade, signedTx string) (string, error) {
	ret := _m.Called(ctx, trade, signedTx)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTrade")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Trade, string) (string, error)); ok {
		return rf(ctx, trade, signedTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Trade, string) string); ok {
		r0 = rf(ctx, trade, signedTx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Trade, string) error); ok {
		r1 = rf(ctx, trade, signedTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_ExecuteTrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteTrade'
type MockClientAPI_ExecuteTrade_Call struct {
	*mock.Call
}

// ExecuteTrade is a helper method to define mock.On call
//   - ctx context.Context
//   - trade *model.Trade
//   - signedTx string
func (_e *MockClientAPI_Expecter) ExecuteTrade(ctx interface{}, trade interface{}, signedTx interface{}) *MockClientAPI_ExecuteTrade_Call {
	return &MockClientAPI_ExecuteTrade_Call{Call: _e.mock.On("ExecuteTrade", ctx, trade, signedTx)}
}

func (_c *MockClientAPI_ExecuteTrade_Call) Run(run func(ctx context.Context, trade *model.Trade, signedTx string)) *MockClientAPI_ExecuteTrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Trade), args[2].(string))
	})
	return _c
}

func (_c *MockClientAPI_ExecuteTrade_Call) Return(_a0 string, _a1 error) *MockClientAPI_ExecuteTrade_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_ExecuteTrade_Call) RunAndReturn(run func(context.Context, *model.Trade, string) (string, error)) *MockClientAPI_ExecuteTrade_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetadataAccount provides a mock function with given fields: ctx, mint
func (_m *MockClientAPI) GetMetadataAccount(ctx context.Context, mint string) (*token_metadata.Metadata, error) {
	ret := _m.Called(ctx, mint)

	if len(ret) == 0 {
		panic("no return value specified for GetMetadataAccount")
	}

	var r0 *token_metadata.Metadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*token_metadata.Metadata, error)); ok {
		return rf(ctx, mint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *token_metadata.Metadata); ok {
		r0 = rf(ctx, mint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token_metadata.Metadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, mint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_GetMetadataAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadataAccount'
type MockClientAPI_GetMetadataAccount_Call struct {
	*mock.Call
}

// GetMetadataAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - mint string
func (_e *MockClientAPI_Expecter) GetMetadataAccount(ctx interface{}, mint interface{}) *MockClientAPI_GetMetadataAccount_Call {
	return &MockClientAPI_GetMetadataAccount_Call{Call: _e.mock.On("GetMetadataAccount", ctx, mint)}
}

func (_c *MockClientAPI_GetMetadataAccount_Call) Run(run func(ctx context.Context, mint string)) *MockClientAPI_GetMetadataAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClientAPI_GetMetadataAccount_Call) Return(_a0 *token_metadata.Metadata, _a1 error) *MockClientAPI_GetMetadataAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_GetMetadataAccount_Call) RunAndReturn(run func(context.Context, string) (*token_metadata.Metadata, error)) *MockClientAPI_GetMetadataAccount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientAPI creates a new instance of MockClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientAPI {
	mock := &MockClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
