// Code generated by mockery v2.53.4. DO NOT EDIT.

package solanamocks

import (
	context "context"

	model "github.com/nicolas-martin/dankfolio/backend/internal/model"
	mock "github.com/stretchr/testify/mock"

	rpc "github.com/gagliardetto/solana-go/rpc"

	solana "github.com/gagliardetto/solana-go"

	token_metadata "github.com/blocto/solana-go-sdk/program/metaplex/token_metadata"
)

// MockClientAPI is an autogenerated mock type for the ClientAPI type
type MockClientAPI struct {
	mock.Mock
}

type MockClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientAPI) EXPECT() *MockClientAPI_Expecter {
	return &MockClientAPI_Expecter{mock: &_m.Mock}
}

// ExecuteSignedTransaction provides a mock function with given fields: ctx, signedTx
func (_m *MockClientAPI) ExecuteSignedTransaction(ctx context.Context, signedTx string) (solana.Signature, error) {
	ret := _m.Called(ctx, signedTx)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteSignedTransaction")
	}

	var r0 solana.Signature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (solana.Signature, error)); ok {
		return rf(ctx, signedTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) solana.Signature); ok {
		r0 = rf(ctx, signedTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(solana.Signature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, signedTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_ExecuteSignedTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteSignedTransaction'
type MockClientAPI_ExecuteSignedTransaction_Call struct {
	*mock.Call
}

// ExecuteSignedTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - signedTx string
func (_e *MockClientAPI_Expecter) ExecuteSignedTransaction(ctx interface{}, signedTx interface{}) *MockClientAPI_ExecuteSignedTransaction_Call {
	return &MockClientAPI_ExecuteSignedTransaction_Call{Call: _e.mock.On("ExecuteSignedTransaction", ctx, signedTx)}
}

func (_c *MockClientAPI_ExecuteSignedTransaction_Call) Run(run func(ctx context.Context, signedTx string)) *MockClientAPI_ExecuteSignedTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClientAPI_ExecuteSignedTransaction_Call) Return(_a0 solana.Signature, _a1 error) *MockClientAPI_ExecuteSignedTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_ExecuteSignedTransaction_Call) RunAndReturn(run func(context.Context, string) (solana.Signature, error)) *MockClientAPI_ExecuteSignedTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteTrade provides a mock function with given fields: ctx, trade, signedTx
func (_m *MockClientAPI) ExecuteTrade(ctx context.Context, trade *model.Trade, signedTx string) (string, error) {
	ret := _m.Called(ctx, trade, signedTx)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTrade")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Trade, string) (string, error)); ok {
		return rf(ctx, trade, signedTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Trade, string) string); ok {
		r0 = rf(ctx, trade, signedTx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Trade, string) error); ok {
		r1 = rf(ctx, trade, signedTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_ExecuteTrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteTrade'
type MockClientAPI_ExecuteTrade_Call struct {
	*mock.Call
}

// ExecuteTrade is a helper method to define mock.On call
//   - ctx context.Context
//   - trade *model.Trade
//   - signedTx string
func (_e *MockClientAPI_Expecter) ExecuteTrade(ctx interface{}, trade interface{}, signedTx interface{}) *MockClientAPI_ExecuteTrade_Call {
	return &MockClientAPI_ExecuteTrade_Call{Call: _e.mock.On("ExecuteTrade", ctx, trade, signedTx)}
}

func (_c *MockClientAPI_ExecuteTrade_Call) Run(run func(ctx context.Context, trade *model.Trade, signedTx string)) *MockClientAPI_ExecuteTrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Trade), args[2].(string))
	})
	return _c
}

func (_c *MockClientAPI_ExecuteTrade_Call) Return(_a0 string, _a1 error) *MockClientAPI_ExecuteTrade_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_ExecuteTrade_Call) RunAndReturn(run func(context.Context, *model.Trade, string) (string, error)) *MockClientAPI_ExecuteTrade_Call {
	_c.Call.Return(run)
	return _c
}

// GetLargestAccounts provides a mock function with given fields: ctx, commitment, filter
func (_m *MockClientAPI) GetLargestAccounts(ctx context.Context, commitment rpc.CommitmentType, filter rpc.LargestAccountsFilterType) (*rpc.GetLargestAccountsResult, error) {
	ret := _m.Called(ctx, commitment, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetLargestAccounts")
	}

	var r0 *rpc.GetLargestAccountsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, rpc.CommitmentType, rpc.LargestAccountsFilterType) (*rpc.GetLargestAccountsResult, error)); ok {
		return rf(ctx, commitment, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, rpc.CommitmentType, rpc.LargestAccountsFilterType) *rpc.GetLargestAccountsResult); ok {
		r0 = rf(ctx, commitment, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetLargestAccountsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, rpc.CommitmentType, rpc.LargestAccountsFilterType) error); ok {
		r1 = rf(ctx, commitment, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_GetLargestAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLargestAccounts'
type MockClientAPI_GetLargestAccounts_Call struct {
	*mock.Call
}

// GetLargestAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - commitment rpc.CommitmentType
//   - filter rpc.LargestAccountsFilterType
func (_e *MockClientAPI_Expecter) GetLargestAccounts(ctx interface{}, commitment interface{}, filter interface{}) *MockClientAPI_GetLargestAccounts_Call {
	return &MockClientAPI_GetLargestAccounts_Call{Call: _e.mock.On("GetLargestAccounts", ctx, commitment, filter)}
}

func (_c *MockClientAPI_GetLargestAccounts_Call) Run(run func(ctx context.Context, commitment rpc.CommitmentType, filter rpc.LargestAccountsFilterType)) *MockClientAPI_GetLargestAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rpc.CommitmentType), args[2].(rpc.LargestAccountsFilterType))
	})
	return _c
}

func (_c *MockClientAPI_GetLargestAccounts_Call) Return(_a0 *rpc.GetLargestAccountsResult, _a1 error) *MockClientAPI_GetLargestAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_GetLargestAccounts_Call) RunAndReturn(run func(context.Context, rpc.CommitmentType, rpc.LargestAccountsFilterType) (*rpc.GetLargestAccountsResult, error)) *MockClientAPI_GetLargestAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetadataAccount provides a mock function with given fields: ctx, mint
func (_m *MockClientAPI) GetMetadataAccount(ctx context.Context, mint string) (*token_metadata.Metadata, error) {
	ret := _m.Called(ctx, mint)

	if len(ret) == 0 {
		panic("no return value specified for GetMetadataAccount")
	}

	var r0 *token_metadata.Metadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*token_metadata.Metadata, error)); ok {
		return rf(ctx, mint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *token_metadata.Metadata); ok {
		r0 = rf(ctx, mint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token_metadata.Metadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, mint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_GetMetadataAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadataAccount'
type MockClientAPI_GetMetadataAccount_Call struct {
	*mock.Call
}

// GetMetadataAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - mint string
func (_e *MockClientAPI_Expecter) GetMetadataAccount(ctx interface{}, mint interface{}) *MockClientAPI_GetMetadataAccount_Call {
	return &MockClientAPI_GetMetadataAccount_Call{Call: _e.mock.On("GetMetadataAccount", ctx, mint)}
}

func (_c *MockClientAPI_GetMetadataAccount_Call) Run(run func(ctx context.Context, mint string)) *MockClientAPI_GetMetadataAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClientAPI_GetMetadataAccount_Call) Return(_a0 *token_metadata.Metadata, _a1 error) *MockClientAPI_GetMetadataAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_GetMetadataAccount_Call) RunAndReturn(run func(context.Context, string) (*token_metadata.Metadata, error)) *MockClientAPI_GetMetadataAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetProgramAccounts provides a mock function with given fields: ctx, pubkey
func (_m *MockClientAPI) GetProgramAccounts(ctx context.Context, pubkey solana.PublicKey) (*rpc.GetProgramAccountsResult, error) {
	ret := _m.Called(ctx, pubkey)

	if len(ret) == 0 {
		panic("no return value specified for GetProgramAccounts")
	}

	var r0 *rpc.GetProgramAccountsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey) (*rpc.GetProgramAccountsResult, error)); ok {
		return rf(ctx, pubkey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey) *rpc.GetProgramAccountsResult); ok {
		r0 = rf(ctx, pubkey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetProgramAccountsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, solana.PublicKey) error); ok {
		r1 = rf(ctx, pubkey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_GetProgramAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProgramAccounts'
type MockClientAPI_GetProgramAccounts_Call struct {
	*mock.Call
}

// GetProgramAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - pubkey solana.PublicKey
func (_e *MockClientAPI_Expecter) GetProgramAccounts(ctx interface{}, pubkey interface{}) *MockClientAPI_GetProgramAccounts_Call {
	return &MockClientAPI_GetProgramAccounts_Call{Call: _e.mock.On("GetProgramAccounts", ctx, pubkey)}
}

func (_c *MockClientAPI_GetProgramAccounts_Call) Run(run func(ctx context.Context, pubkey solana.PublicKey)) *MockClientAPI_GetProgramAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(solana.PublicKey))
	})
	return _c
}

func (_c *MockClientAPI_GetProgramAccounts_Call) Return(_a0 *rpc.GetProgramAccountsResult, _a1 error) *MockClientAPI_GetProgramAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_GetProgramAccounts_Call) RunAndReturn(run func(context.Context, solana.PublicKey) (*rpc.GetProgramAccountsResult, error)) *MockClientAPI_GetProgramAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// GetSupply provides a mock function with given fields: ctx, commitment
func (_m *MockClientAPI) GetSupply(ctx context.Context, commitment rpc.CommitmentType) (*rpc.GetSupplyResult, error) {
	ret := _m.Called(ctx, commitment)

	if len(ret) == 0 {
		panic("no return value specified for GetSupply")
	}

	var r0 *rpc.GetSupplyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, rpc.CommitmentType) (*rpc.GetSupplyResult, error)); ok {
		return rf(ctx, commitment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, rpc.CommitmentType) *rpc.GetSupplyResult); ok {
		r0 = rf(ctx, commitment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetSupplyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, rpc.CommitmentType) error); ok {
		r1 = rf(ctx, commitment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_GetSupply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSupply'
type MockClientAPI_GetSupply_Call struct {
	*mock.Call
}

// GetSupply is a helper method to define mock.On call
//   - ctx context.Context
//   - commitment rpc.CommitmentType
func (_e *MockClientAPI_Expecter) GetSupply(ctx interface{}, commitment interface{}) *MockClientAPI_GetSupply_Call {
	return &MockClientAPI_GetSupply_Call{Call: _e.mock.On("GetSupply", ctx, commitment)}
}

func (_c *MockClientAPI_GetSupply_Call) Run(run func(ctx context.Context, commitment rpc.CommitmentType)) *MockClientAPI_GetSupply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rpc.CommitmentType))
	})
	return _c
}

func (_c *MockClientAPI_GetSupply_Call) Return(_a0 *rpc.GetSupplyResult, _a1 error) *MockClientAPI_GetSupply_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_GetSupply_Call) RunAndReturn(run func(context.Context, rpc.CommitmentType) (*rpc.GetSupplyResult, error)) *MockClientAPI_GetSupply_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenAccountsByOwner provides a mock function with given fields: ctx, owner, mint, encoding
func (_m *MockClientAPI) GetTokenAccountsByOwner(ctx context.Context, owner solana.PublicKey, mint solana.PublicKey, encoding solana.EncodingType) (*rpc.GetTokenAccountsResult, error) {
	ret := _m.Called(ctx, owner, mint, encoding)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenAccountsByOwner")
	}

	var r0 *rpc.GetTokenAccountsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey, solana.PublicKey, solana.EncodingType) (*rpc.GetTokenAccountsResult, error)); ok {
		return rf(ctx, owner, mint, encoding)
	}
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey, solana.PublicKey, solana.EncodingType) *rpc.GetTokenAccountsResult); ok {
		r0 = rf(ctx, owner, mint, encoding)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetTokenAccountsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, solana.PublicKey, solana.PublicKey, solana.EncodingType) error); ok {
		r1 = rf(ctx, owner, mint, encoding)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_GetTokenAccountsByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenAccountsByOwner'
type MockClientAPI_GetTokenAccountsByOwner_Call struct {
	*mock.Call
}

// GetTokenAccountsByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - owner solana.PublicKey
//   - mint solana.PublicKey
//   - encoding solana.EncodingType
func (_e *MockClientAPI_Expecter) GetTokenAccountsByOwner(ctx interface{}, owner interface{}, mint interface{}, encoding interface{}) *MockClientAPI_GetTokenAccountsByOwner_Call {
	return &MockClientAPI_GetTokenAccountsByOwner_Call{Call: _e.mock.On("GetTokenAccountsByOwner", ctx, owner, mint, encoding)}
}

func (_c *MockClientAPI_GetTokenAccountsByOwner_Call) Run(run func(ctx context.Context, owner solana.PublicKey, mint solana.PublicKey, encoding solana.EncodingType)) *MockClientAPI_GetTokenAccountsByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(solana.PublicKey), args[2].(solana.PublicKey), args[3].(solana.EncodingType))
	})
	return _c
}

func (_c *MockClientAPI_GetTokenAccountsByOwner_Call) Return(_a0 *rpc.GetTokenAccountsResult, _a1 error) *MockClientAPI_GetTokenAccountsByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_GetTokenAccountsByOwner_Call) RunAndReturn(run func(context.Context, solana.PublicKey, solana.PublicKey, solana.EncodingType) (*rpc.GetTokenAccountsResult, error)) *MockClientAPI_GetTokenAccountsByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionConfirmationStatus provides a mock function with given fields: ctx, sigStr
func (_m *MockClientAPI) GetTransactionConfirmationStatus(ctx context.Context, sigStr string) (*rpc.GetSignatureStatusesResult, error) {
	ret := _m.Called(ctx, sigStr)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionConfirmationStatus")
	}

	var r0 *rpc.GetSignatureStatusesResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*rpc.GetSignatureStatusesResult, error)); ok {
		return rf(ctx, sigStr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *rpc.GetSignatureStatusesResult); ok {
		r0 = rf(ctx, sigStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetSignatureStatusesResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sigStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_GetTransactionConfirmationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionConfirmationStatus'
type MockClientAPI_GetTransactionConfirmationStatus_Call struct {
	*mock.Call
}

// GetTransactionConfirmationStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - sigStr string
func (_e *MockClientAPI_Expecter) GetTransactionConfirmationStatus(ctx interface{}, sigStr interface{}) *MockClientAPI_GetTransactionConfirmationStatus_Call {
	return &MockClientAPI_GetTransactionConfirmationStatus_Call{Call: _e.mock.On("GetTransactionConfirmationStatus", ctx, sigStr)}
}

func (_c *MockClientAPI_GetTransactionConfirmationStatus_Call) Run(run func(ctx context.Context, sigStr string)) *MockClientAPI_GetTransactionConfirmationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClientAPI_GetTransactionConfirmationStatus_Call) Return(_a0 *rpc.GetSignatureStatusesResult, _a1 error) *MockClientAPI_GetTransactionConfirmationStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_GetTransactionConfirmationStatus_Call) RunAndReturn(run func(context.Context, string) (*rpc.GetSignatureStatusesResult, error)) *MockClientAPI_GetTransactionConfirmationStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientAPI creates a new instance of MockClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientAPI {
	mock := &MockClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
