// Code generated by mockery. DO NOT EDIT.

package solanaMocks

import (
	context "context"

	solana "github.com/gagliardetto/solana-go"
	rpc "github.com/gagliardetto/solana-go/rpc"
	mock "github.com/stretchr/testify/mock"
)

// SolanaRPCClientAPI is an autogenerated mock type for the SolanaRPCClientAPI type
type SolanaRPCClientAPI struct {
	mock.Mock
}

// GetAccountInfo provides a mock function with given fields: ctx, account
func (_m *SolanaRPCClientAPI) GetAccountInfo(ctx context.Context, account solana.PublicKey) (*rpc.GetAccountInfoResult, error) {
	ret := _m.Called(ctx, account)

	var r0 *rpc.GetAccountInfoResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey) (*rpc.GetAccountInfoResult, error)); ok {
		return rf(ctx, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey) *rpc.GetAccountInfoResult); ok {
		r0 = rf(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetAccountInfoResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, solana.PublicKey) error); ok {
		r1 = rf(ctx, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBalance provides a mock function with given fields: ctx, account, commitment
func (_m *SolanaRPCClientAPI) GetBalance(ctx context.Context, account solana.PublicKey, commitment rpc.CommitmentType) (*rpc.GetBalanceResult, error) {
	ret := _m.Called(ctx, account, commitment)

	var r0 *rpc.GetBalanceResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey, rpc.CommitmentType) (*rpc.GetBalanceResult, error)); ok {
		return rf(ctx, account, commitment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey, rpc.CommitmentType) *rpc.GetBalanceResult); ok {
		r0 = rf(ctx, account, commitment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetBalanceResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, solana.PublicKey, rpc.CommitmentType) error); ok {
		r1 = rf(ctx, account, commitment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestBlockhash provides a mock function with given fields: ctx, commitment
func (_m *SolanaRPCClientAPI) GetLatestBlockhash(ctx context.Context, commitment rpc.CommitmentType) (*rpc.GetLatestBlockhashResult, error) {
	ret := _m.Called(ctx, commitment)

	var r0 *rpc.GetLatestBlockhashResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, rpc.CommitmentType) (*rpc.GetLatestBlockhashResult, error)); ok {
		return rf(ctx, commitment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, rpc.CommitmentType) *rpc.GetLatestBlockhashResult); ok {
		r0 = rf(ctx, commitment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetLatestBlockhashResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, rpc.CommitmentType) error); ok {
		r1 = rf(ctx, commitment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTokenAccountsByOwner provides a mock function with given fields: ctx, owner, mint, opts
func (_m *SolanaRPCClientAPI) GetTokenAccountsByOwner(ctx context.Context, owner solana.PublicKey, mint *rpc.GetTokenAccountsConfig, opts *rpc.GetTokenAccountsOpts) (*rpc.GetTokenAccountsResult, error) { // Corrected return type
	ret := _m.Called(ctx, owner, mint, opts)

	var r0 *rpc.GetTokenAccountsResult // Corrected type
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey, *rpc.GetTokenAccountsConfig, *rpc.GetTokenAccountsOpts) (*rpc.GetTokenAccountsResult, error)); ok { // Corrected type
		return rf(ctx, owner, mint, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey, *rpc.GetTokenAccountsConfig, *rpc.GetTokenAccountsOpts) *rpc.GetTokenAccountsResult); ok { // Corrected type
		r0 = rf(ctx, owner, mint, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetTokenAccountsResult) // Corrected type
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, solana.PublicKey, *rpc.GetTokenAccountsConfig, *rpc.GetTokenAccountsOpts) error); ok {
		r1 = rf(ctx, owner, mint, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendTransactionWithOpts provides a mock function with given fields: ctx, tx, opts
func (_m *SolanaRPCClientAPI) SendTransactionWithOpts(ctx context.Context, tx *solana.Transaction, opts rpc.TransactionOpts) (solana.Signature, error) {
	ret := _m.Called(ctx, tx, opts)

	var r0 solana.Signature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *solana.Transaction, rpc.TransactionOpts) (solana.Signature, error)); ok {
		return rf(ctx, tx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *solana.Transaction, rpc.TransactionOpts) solana.Signature); ok {
		r0 = rf(ctx, tx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(solana.Signature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *solana.Transaction, rpc.TransactionOpts) error); ok {
		r1 = rf(ctx, tx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSolanaRPCClientAPI creates a new instance of SolanaRPCClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSolanaRPCClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *SolanaRPCClientAPI {
	mock := &SolanaRPCClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
