// Code generated by mockery v2.53.4. DO NOT EDIT.

package solanamocks

import (
	context "context"

	model "github.com/nicolas-martin/dankfolio/backend/internal/model"
	mock "github.com/stretchr/testify/mock"

	rpc "github.com/gagliardetto/solana-go/rpc"

	solana "github.com/gagliardetto/solana-go"
)

// MockSolanaRPCClientAPI is an autogenerated mock type for the SolanaRPCClientAPI type
type MockSolanaRPCClientAPI struct {
	mock.Mock
}

type MockSolanaRPCClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSolanaRPCClientAPI) EXPECT() *MockSolanaRPCClientAPI_Expecter {
	return &MockSolanaRPCClientAPI_Expecter{mock: &_m.Mock}
}

// GetAccountInfo provides a mock function with given fields: ctx, account
func (_m *MockSolanaRPCClientAPI) GetAccountInfo(ctx context.Context, account solana.PublicKey) (*rpc.GetAccountInfoResult, error) {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountInfo")
	}

	var r0 *rpc.GetAccountInfoResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey) (*rpc.GetAccountInfoResult, error)); ok {
		return rf(ctx, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey) *rpc.GetAccountInfoResult); ok {
		r0 = rf(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetAccountInfoResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, solana.PublicKey) error); ok {
		r1 = rf(ctx, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSolanaRPCClientAPI_GetAccountInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountInfo'
type MockSolanaRPCClientAPI_GetAccountInfo_Call struct {
	*mock.Call
}

// GetAccountInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - account solana.PublicKey
func (_e *MockSolanaRPCClientAPI_Expecter) GetAccountInfo(ctx interface{}, account interface{}) *MockSolanaRPCClientAPI_GetAccountInfo_Call {
	return &MockSolanaRPCClientAPI_GetAccountInfo_Call{Call: _e.mock.On("GetAccountInfo", ctx, account)}
}

func (_c *MockSolanaRPCClientAPI_GetAccountInfo_Call) Run(run func(ctx context.Context, account solana.PublicKey)) *MockSolanaRPCClientAPI_GetAccountInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(solana.PublicKey))
	})
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetAccountInfo_Call) Return(_a0 *rpc.GetAccountInfoResult, _a1 error) *MockSolanaRPCClientAPI_GetAccountInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetAccountInfo_Call) RunAndReturn(run func(context.Context, solana.PublicKey) (*rpc.GetAccountInfoResult, error)) *MockSolanaRPCClientAPI_GetAccountInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalanceConfirmed provides a mock function with given fields: ctx, account
func (_m *MockSolanaRPCClientAPI) GetBalanceConfirmed(ctx context.Context, account solana.PublicKey) (*rpc.GetBalanceResult, error) {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for GetBalanceConfirmed")
	}

	var r0 *rpc.GetBalanceResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey) (*rpc.GetBalanceResult, error)); ok {
		return rf(ctx, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey) *rpc.GetBalanceResult); ok {
		r0 = rf(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetBalanceResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, solana.PublicKey) error); ok {
		r1 = rf(ctx, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSolanaRPCClientAPI_GetBalanceConfirmed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalanceConfirmed'
type MockSolanaRPCClientAPI_GetBalanceConfirmed_Call struct {
	*mock.Call
}

// GetBalanceConfirmed is a helper method to define mock.On call
//   - ctx context.Context
//   - account solana.PublicKey
func (_e *MockSolanaRPCClientAPI_Expecter) GetBalanceConfirmed(ctx interface{}, account interface{}) *MockSolanaRPCClientAPI_GetBalanceConfirmed_Call {
	return &MockSolanaRPCClientAPI_GetBalanceConfirmed_Call{Call: _e.mock.On("GetBalanceConfirmed", ctx, account)}
}

func (_c *MockSolanaRPCClientAPI_GetBalanceConfirmed_Call) Run(run func(ctx context.Context, account solana.PublicKey)) *MockSolanaRPCClientAPI_GetBalanceConfirmed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(solana.PublicKey))
	})
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetBalanceConfirmed_Call) Return(_a0 *rpc.GetBalanceResult, _a1 error) *MockSolanaRPCClientAPI_GetBalanceConfirmed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetBalanceConfirmed_Call) RunAndReturn(run func(context.Context, solana.PublicKey) (*rpc.GetBalanceResult, error)) *MockSolanaRPCClientAPI_GetBalanceConfirmed_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestBlockhashConfirmed provides a mock function with given fields: ctx
func (_m *MockSolanaRPCClientAPI) GetLatestBlockhashConfirmed(ctx context.Context) (*rpc.GetLatestBlockhashResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBlockhashConfirmed")
	}

	var r0 *rpc.GetLatestBlockhashResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*rpc.GetLatestBlockhashResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *rpc.GetLatestBlockhashResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetLatestBlockhashResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSolanaRPCClientAPI_GetLatestBlockhashConfirmed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestBlockhashConfirmed'
type MockSolanaRPCClientAPI_GetLatestBlockhashConfirmed_Call struct {
	*mock.Call
}

// GetLatestBlockhashConfirmed is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSolanaRPCClientAPI_Expecter) GetLatestBlockhashConfirmed(ctx interface{}) *MockSolanaRPCClientAPI_GetLatestBlockhashConfirmed_Call {
	return &MockSolanaRPCClientAPI_GetLatestBlockhashConfirmed_Call{Call: _e.mock.On("GetLatestBlockhashConfirmed", ctx)}
}

func (_c *MockSolanaRPCClientAPI_GetLatestBlockhashConfirmed_Call) Run(run func(ctx context.Context)) *MockSolanaRPCClientAPI_GetLatestBlockhashConfirmed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetLatestBlockhashConfirmed_Call) Return(_a0 *rpc.GetLatestBlockhashResult, _a1 error) *MockSolanaRPCClientAPI_GetLatestBlockhashConfirmed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetLatestBlockhashConfirmed_Call) RunAndReturn(run func(context.Context) (*rpc.GetLatestBlockhashResult, error)) *MockSolanaRPCClientAPI_GetLatestBlockhashConfirmed_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenAccountsByOwnerConfirmed provides a mock function with given fields: ctx, owner, opts
func (_m *MockSolanaRPCClientAPI) GetTokenAccountsByOwnerConfirmed(ctx context.Context, owner solana.PublicKey, opts model.GetTokenAccountsOptions) (*rpc.GetTokenAccountsResult, error) {
	ret := _m.Called(ctx, owner, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenAccountsByOwnerConfirmed")
	}

	var r0 *rpc.GetTokenAccountsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey, model.GetTokenAccountsOptions) (*rpc.GetTokenAccountsResult, error)); ok {
		return rf(ctx, owner, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey, model.GetTokenAccountsOptions) *rpc.GetTokenAccountsResult); ok {
		r0 = rf(ctx, owner, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetTokenAccountsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, solana.PublicKey, model.GetTokenAccountsOptions) error); ok {
		r1 = rf(ctx, owner, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSolanaRPCClientAPI_GetTokenAccountsByOwnerConfirmed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenAccountsByOwnerConfirmed'
type MockSolanaRPCClientAPI_GetTokenAccountsByOwnerConfirmed_Call struct {
	*mock.Call
}

// GetTokenAccountsByOwnerConfirmed is a helper method to define mock.On call
//   - ctx context.Context
//   - owner solana.PublicKey
//   - opts model.GetTokenAccountsOptions
func (_e *MockSolanaRPCClientAPI_Expecter) GetTokenAccountsByOwnerConfirmed(ctx interface{}, owner interface{}, opts interface{}) *MockSolanaRPCClientAPI_GetTokenAccountsByOwnerConfirmed_Call {
	return &MockSolanaRPCClientAPI_GetTokenAccountsByOwnerConfirmed_Call{Call: _e.mock.On("GetTokenAccountsByOwnerConfirmed", ctx, owner, opts)}
}

func (_c *MockSolanaRPCClientAPI_GetTokenAccountsByOwnerConfirmed_Call) Run(run func(ctx context.Context, owner solana.PublicKey, opts model.GetTokenAccountsOptions)) *MockSolanaRPCClientAPI_GetTokenAccountsByOwnerConfirmed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(solana.PublicKey), args[2].(model.GetTokenAccountsOptions))
	})
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetTokenAccountsByOwnerConfirmed_Call) Return(_a0 *rpc.GetTokenAccountsResult, _a1 error) *MockSolanaRPCClientAPI_GetTokenAccountsByOwnerConfirmed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetTokenAccountsByOwnerConfirmed_Call) RunAndReturn(run func(context.Context, solana.PublicKey, model.GetTokenAccountsOptions) (*rpc.GetTokenAccountsResult, error)) *MockSolanaRPCClientAPI_GetTokenAccountsByOwnerConfirmed_Call {
	_c.Call.Return(run)
	return _c
}

// SendTransactionWithCustomOpts provides a mock function with given fields: ctx, tx, opts
func (_m *MockSolanaRPCClientAPI) SendTransactionWithCustomOpts(ctx context.Context, tx *solana.Transaction, opts model.TransactionOptions) (solana.Signature, error) {
	ret := _m.Called(ctx, tx, opts)

	if len(ret) == 0 {
		panic("no return value specified for SendTransactionWithCustomOpts")
	}

	var r0 solana.Signature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *solana.Transaction, model.TransactionOptions) (solana.Signature, error)); ok {
		return rf(ctx, tx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *solana.Transaction, model.TransactionOptions) solana.Signature); ok {
		r0 = rf(ctx, tx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(solana.Signature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *solana.Transaction, model.TransactionOptions) error); ok {
		r1 = rf(ctx, tx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSolanaRPCClientAPI_SendTransactionWithCustomOpts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTransactionWithCustomOpts'
type MockSolanaRPCClientAPI_SendTransactionWithCustomOpts_Call struct {
	*mock.Call
}

// SendTransactionWithCustomOpts is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *solana.Transaction
//   - opts model.TransactionOptions
func (_e *MockSolanaRPCClientAPI_Expecter) SendTransactionWithCustomOpts(ctx interface{}, tx interface{}, opts interface{}) *MockSolanaRPCClientAPI_SendTransactionWithCustomOpts_Call {
	return &MockSolanaRPCClientAPI_SendTransactionWithCustomOpts_Call{Call: _e.mock.On("SendTransactionWithCustomOpts", ctx, tx, opts)}
}

func (_c *MockSolanaRPCClientAPI_SendTransactionWithCustomOpts_Call) Run(run func(ctx context.Context, tx *solana.Transaction, opts model.TransactionOptions)) *MockSolanaRPCClientAPI_SendTransactionWithCustomOpts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*solana.Transaction), args[2].(model.TransactionOptions))
	})
	return _c
}

func (_c *MockSolanaRPCClientAPI_SendTransactionWithCustomOpts_Call) Return(_a0 solana.Signature, _a1 error) *MockSolanaRPCClientAPI_SendTransactionWithCustomOpts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSolanaRPCClientAPI_SendTransactionWithCustomOpts_Call) RunAndReturn(run func(context.Context, *solana.Transaction, model.TransactionOptions) (solana.Signature, error)) *MockSolanaRPCClientAPI_SendTransactionWithCustomOpts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSolanaRPCClientAPI creates a new instance of MockSolanaRPCClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSolanaRPCClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSolanaRPCClientAPI {
	mock := &MockSolanaRPCClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
