// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package solanaMocks

import (
	"context"

	"github.com/gagliardetto/solana-go"
	"github.com/gagliardetto/solana-go/rpc"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSolanaRPCClientAPI creates a new instance of MockSolanaRPCClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSolanaRPCClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSolanaRPCClientAPI {
	mock := &MockSolanaRPCClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSolanaRPCClientAPI is an autogenerated mock type for the SolanaRPCClientAPI type
type MockSolanaRPCClientAPI struct {
	mock.Mock
}

type MockSolanaRPCClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSolanaRPCClientAPI) EXPECT() *MockSolanaRPCClientAPI_Expecter {
	return &MockSolanaRPCClientAPI_Expecter{mock: &_m.Mock}
}

// GetAccountInfo provides a mock function for the type MockSolanaRPCClientAPI
func (_mock *MockSolanaRPCClientAPI) GetAccountInfo(ctx context.Context, account solana.PublicKey) (*rpc.GetAccountInfoResult, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountInfo")
	}

	var r0 *rpc.GetAccountInfoResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, solana.PublicKey) (*rpc.GetAccountInfoResult, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, solana.PublicKey) *rpc.GetAccountInfoResult); ok {
		r0 = returnFunc(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetAccountInfoResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, solana.PublicKey) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSolanaRPCClientAPI_GetAccountInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountInfo'
type MockSolanaRPCClientAPI_GetAccountInfo_Call struct {
	*mock.Call
}

// GetAccountInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - account solana.PublicKey
func (_e *MockSolanaRPCClientAPI_Expecter) GetAccountInfo(ctx interface{}, account interface{}) *MockSolanaRPCClientAPI_GetAccountInfo_Call {
	return &MockSolanaRPCClientAPI_GetAccountInfo_Call{Call: _e.mock.On("GetAccountInfo", ctx, account)}
}

func (_c *MockSolanaRPCClientAPI_GetAccountInfo_Call) Run(run func(ctx context.Context, account solana.PublicKey)) *MockSolanaRPCClientAPI_GetAccountInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 solana.PublicKey
		if args[1] != nil {
			arg1 = args[1].(solana.PublicKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetAccountInfo_Call) Return(getAccountInfoResult *rpc.GetAccountInfoResult, err error) *MockSolanaRPCClientAPI_GetAccountInfo_Call {
	_c.Call.Return(getAccountInfoResult, err)
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetAccountInfo_Call) RunAndReturn(run func(ctx context.Context, account solana.PublicKey) (*rpc.GetAccountInfoResult, error)) *MockSolanaRPCClientAPI_GetAccountInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockSolanaRPCClientAPI
func (_mock *MockSolanaRPCClientAPI) GetBalance(ctx context.Context, account solana.PublicKey, commitment rpc.CommitmentType) (*rpc.GetBalanceResult, error) {
	ret := _mock.Called(ctx, account, commitment)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *rpc.GetBalanceResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, solana.PublicKey, rpc.CommitmentType) (*rpc.GetBalanceResult, error)); ok {
		return returnFunc(ctx, account, commitment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, solana.PublicKey, rpc.CommitmentType) *rpc.GetBalanceResult); ok {
		r0 = returnFunc(ctx, account, commitment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetBalanceResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, solana.PublicKey, rpc.CommitmentType) error); ok {
		r1 = returnFunc(ctx, account, commitment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSolanaRPCClientAPI_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockSolanaRPCClientAPI_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - account solana.PublicKey
//   - commitment rpc.CommitmentType
func (_e *MockSolanaRPCClientAPI_Expecter) GetBalance(ctx interface{}, account interface{}, commitment interface{}) *MockSolanaRPCClientAPI_GetBalance_Call {
	return &MockSolanaRPCClientAPI_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, account, commitment)}
}

func (_c *MockSolanaRPCClientAPI_GetBalance_Call) Run(run func(ctx context.Context, account solana.PublicKey, commitment rpc.CommitmentType)) *MockSolanaRPCClientAPI_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 solana.PublicKey
		if args[1] != nil {
			arg1 = args[1].(solana.PublicKey)
		}
		var arg2 rpc.CommitmentType
		if args[2] != nil {
			arg2 = args[2].(rpc.CommitmentType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetBalance_Call) Return(getBalanceResult *rpc.GetBalanceResult, err error) *MockSolanaRPCClientAPI_GetBalance_Call {
	_c.Call.Return(getBalanceResult, err)
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetBalance_Call) RunAndReturn(run func(ctx context.Context, account solana.PublicKey, commitment rpc.CommitmentType) (*rpc.GetBalanceResult, error)) *MockSolanaRPCClientAPI_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestBlockhash provides a mock function for the type MockSolanaRPCClientAPI
func (_mock *MockSolanaRPCClientAPI) GetLatestBlockhash(ctx context.Context, commitment rpc.CommitmentType) (*rpc.GetLatestBlockhashResult, error) {
	ret := _mock.Called(ctx, commitment)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBlockhash")
	}

	var r0 *rpc.GetLatestBlockhashResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, rpc.CommitmentType) (*rpc.GetLatestBlockhashResult, error)); ok {
		return returnFunc(ctx, commitment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, rpc.CommitmentType) *rpc.GetLatestBlockhashResult); ok {
		r0 = returnFunc(ctx, commitment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetLatestBlockhashResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, rpc.CommitmentType) error); ok {
		r1 = returnFunc(ctx, commitment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSolanaRPCClientAPI_GetLatestBlockhash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestBlockhash'
type MockSolanaRPCClientAPI_GetLatestBlockhash_Call struct {
	*mock.Call
}

// GetLatestBlockhash is a helper method to define mock.On call
//   - ctx context.Context
//   - commitment rpc.CommitmentType
func (_e *MockSolanaRPCClientAPI_Expecter) GetLatestBlockhash(ctx interface{}, commitment interface{}) *MockSolanaRPCClientAPI_GetLatestBlockhash_Call {
	return &MockSolanaRPCClientAPI_GetLatestBlockhash_Call{Call: _e.mock.On("GetLatestBlockhash", ctx, commitment)}
}

func (_c *MockSolanaRPCClientAPI_GetLatestBlockhash_Call) Run(run func(ctx context.Context, commitment rpc.CommitmentType)) *MockSolanaRPCClientAPI_GetLatestBlockhash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 rpc.CommitmentType
		if args[1] != nil {
			arg1 = args[1].(rpc.CommitmentType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetLatestBlockhash_Call) Return(getLatestBlockhashResult *rpc.GetLatestBlockhashResult, err error) *MockSolanaRPCClientAPI_GetLatestBlockhash_Call {
	_c.Call.Return(getLatestBlockhashResult, err)
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetLatestBlockhash_Call) RunAndReturn(run func(ctx context.Context, commitment rpc.CommitmentType) (*rpc.GetLatestBlockhashResult, error)) *MockSolanaRPCClientAPI_GetLatestBlockhash_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenAccountsByOwner provides a mock function for the type MockSolanaRPCClientAPI
func (_mock *MockSolanaRPCClientAPI) GetTokenAccountsByOwner(ctx context.Context, owner solana.PublicKey, mint *rpc.GetTokenAccountsConfig, opts *rpc.GetTokenAccountsOpts) (*rpc.GetTokenAccountsResult, error) {
	ret := _mock.Called(ctx, owner, mint, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenAccountsByOwner")
	}

	var r0 *rpc.GetTokenAccountsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, solana.PublicKey, *rpc.GetTokenAccountsConfig, *rpc.GetTokenAccountsOpts) (*rpc.GetTokenAccountsResult, error)); ok {
		return returnFunc(ctx, owner, mint, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, solana.PublicKey, *rpc.GetTokenAccountsConfig, *rpc.GetTokenAccountsOpts) *rpc.GetTokenAccountsResult); ok {
		r0 = returnFunc(ctx, owner, mint, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetTokenAccountsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, solana.PublicKey, *rpc.GetTokenAccountsConfig, *rpc.GetTokenAccountsOpts) error); ok {
		r1 = returnFunc(ctx, owner, mint, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSolanaRPCClientAPI_GetTokenAccountsByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenAccountsByOwner'
type MockSolanaRPCClientAPI_GetTokenAccountsByOwner_Call struct {
	*mock.Call
}

// GetTokenAccountsByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - owner solana.PublicKey
//   - mint *rpc.GetTokenAccountsConfig
//   - opts *rpc.GetTokenAccountsOpts
func (_e *MockSolanaRPCClientAPI_Expecter) GetTokenAccountsByOwner(ctx interface{}, owner interface{}, mint interface{}, opts interface{}) *MockSolanaRPCClientAPI_GetTokenAccountsByOwner_Call {
	return &MockSolanaRPCClientAPI_GetTokenAccountsByOwner_Call{Call: _e.mock.On("GetTokenAccountsByOwner", ctx, owner, mint, opts)}
}

func (_c *MockSolanaRPCClientAPI_GetTokenAccountsByOwner_Call) Run(run func(ctx context.Context, owner solana.PublicKey, mint *rpc.GetTokenAccountsConfig, opts *rpc.GetTokenAccountsOpts)) *MockSolanaRPCClientAPI_GetTokenAccountsByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 solana.PublicKey
		if args[1] != nil {
			arg1 = args[1].(solana.PublicKey)
		}
		var arg2 *rpc.GetTokenAccountsConfig
		if args[2] != nil {
			arg2 = args[2].(*rpc.GetTokenAccountsConfig)
		}
		var arg3 *rpc.GetTokenAccountsOpts
		if args[3] != nil {
			arg3 = args[3].(*rpc.GetTokenAccountsOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetTokenAccountsByOwner_Call) Return(getTokenAccountsResult *rpc.GetTokenAccountsResult, err error) *MockSolanaRPCClientAPI_GetTokenAccountsByOwner_Call {
	_c.Call.Return(getTokenAccountsResult, err)
	return _c
}

func (_c *MockSolanaRPCClientAPI_GetTokenAccountsByOwner_Call) RunAndReturn(run func(ctx context.Context, owner solana.PublicKey, mint *rpc.GetTokenAccountsConfig, opts *rpc.GetTokenAccountsOpts) (*rpc.GetTokenAccountsResult, error)) *MockSolanaRPCClientAPI_GetTokenAccountsByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// SendTransactionWithOpts provides a mock function for the type MockSolanaRPCClientAPI
func (_mock *MockSolanaRPCClientAPI) SendTransactionWithOpts(ctx context.Context, tx *solana.Transaction, opts rpc.TransactionOpts) (solana.Signature, error) {
	ret := _mock.Called(ctx, tx, opts)

	if len(ret) == 0 {
		panic("no return value specified for SendTransactionWithOpts")
	}

	var r0 solana.Signature
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *solana.Transaction, rpc.TransactionOpts) (solana.Signature, error)); ok {
		return returnFunc(ctx, tx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *solana.Transaction, rpc.TransactionOpts) solana.Signature); ok {
		r0 = returnFunc(ctx, tx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(solana.Signature)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *solana.Transaction, rpc.TransactionOpts) error); ok {
		r1 = returnFunc(ctx, tx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSolanaRPCClientAPI_SendTransactionWithOpts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTransactionWithOpts'
type MockSolanaRPCClientAPI_SendTransactionWithOpts_Call struct {
	*mock.Call
}

// SendTransactionWithOpts is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *solana.Transaction
//   - opts rpc.TransactionOpts
func (_e *MockSolanaRPCClientAPI_Expecter) SendTransactionWithOpts(ctx interface{}, tx interface{}, opts interface{}) *MockSolanaRPCClientAPI_SendTransactionWithOpts_Call {
	return &MockSolanaRPCClientAPI_SendTransactionWithOpts_Call{Call: _e.mock.On("SendTransactionWithOpts", ctx, tx, opts)}
}

func (_c *MockSolanaRPCClientAPI_SendTransactionWithOpts_Call) Run(run func(ctx context.Context, tx *solana.Transaction, opts rpc.TransactionOpts)) *MockSolanaRPCClientAPI_SendTransactionWithOpts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *solana.Transaction
		if args[1] != nil {
			arg1 = args[1].(*solana.Transaction)
		}
		var arg2 rpc.TransactionOpts
		if args[2] != nil {
			arg2 = args[2].(rpc.TransactionOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSolanaRPCClientAPI_SendTransactionWithOpts_Call) Return(signature solana.Signature, err error) *MockSolanaRPCClientAPI_SendTransactionWithOpts_Call {
	_c.Call.Return(signature, err)
	return _c
}

func (_c *MockSolanaRPCClientAPI_SendTransactionWithOpts_Call) RunAndReturn(run func(ctx context.Context, tx *solana.Transaction, opts rpc.TransactionOpts) (solana.Signature, error)) *MockSolanaRPCClientAPI_SendTransactionWithOpts_Call {
	_c.Call.Return(run)
	return _c
}
