// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dbMocks

import (
	"context"

	"github.com/nicolas-martin/dankfolio/backend/internal/db"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository[T db.Entity](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository[T] {
	mock := &MockRepository[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository[T db.Entity] struct {
	mock.Mock
}

type MockRepository_Expecter[T db.Entity] struct {
	mock *mock.Mock
}

func (_m *MockRepository[T]) EXPECT() *MockRepository_Expecter[T] {
	return &MockRepository_Expecter[T]{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) Create(ctx context.Context, item *T) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *T) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call[T db.Entity] struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - item
func (_e *MockRepository_Expecter[T]) Create(ctx interface{}, item interface{}) *MockRepository_Create_Call[T] {
	return &MockRepository_Create_Call[T]{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *MockRepository_Create_Call[T]) Run(run func(ctx context.Context, item *T)) *MockRepository_Create_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*T))
	})
	return _c
}

func (_c *MockRepository_Create_Call[T]) Return(err error) *MockRepository_Create_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call[T]) RunAndReturn(run func(ctx context.Context, item *T) error) *MockRepository_Create_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call[T db.Entity] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockRepository_Expecter[T]) Delete(ctx interface{}, id interface{}) *MockRepository_Delete_Call[T] {
	return &MockRepository_Delete_Call[T]{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call[T]) Run(run func(ctx context.Context, id string)) *MockRepository_Delete_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_Delete_Call[T]) Return(err error) *MockRepository_Delete_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call[T]) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_Delete_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) Get(ctx context.Context, id string) (*T, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*T, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *T); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call[T db.Entity] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockRepository_Expecter[T]) Get(ctx interface{}, id interface{}) *MockRepository_Get_Call[T] {
	return &MockRepository_Get_Call[T]{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRepository_Get_Call[T]) Run(run func(ctx context.Context, id string)) *MockRepository_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_Get_Call[T]) Return(v *T, err error) *MockRepository_Get_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepository_Get_Call[T]) RunAndReturn(run func(ctx context.Context, id string) (*T, error)) *MockRepository_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetByField provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) GetByField(ctx context.Context, field string, value any) (*T, error) {
	ret := _mock.Called(ctx, field, value)

	if len(ret) == 0 {
		panic("no return value specified for GetByField")
	}

	var r0 *T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) (*T, error)); ok {
		return returnFunc(ctx, field, value)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) *T); ok {
		r0 = returnFunc(ctx, field, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any) error); ok {
		r1 = returnFunc(ctx, field, value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByField'
type MockRepository_GetByField_Call[T db.Entity] struct {
	*mock.Call
}

// GetByField is a helper method to define mock.On call
//   - ctx
//   - field
//   - value
func (_e *MockRepository_Expecter[T]) GetByField(ctx interface{}, field interface{}, value interface{}) *MockRepository_GetByField_Call[T] {
	return &MockRepository_GetByField_Call[T]{Call: _e.mock.On("GetByField", ctx, field, value)}
}

func (_c *MockRepository_GetByField_Call[T]) Run(run func(ctx context.Context, field string, value any)) *MockRepository_GetByField_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(any))
	})
	return _c
}

func (_c *MockRepository_GetByField_Call[T]) Return(v *T, err error) *MockRepository_GetByField_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepository_GetByField_Call[T]) RunAndReturn(run func(ctx context.Context, field string, value any) (*T, error)) *MockRepository_GetByField_Call[T] {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) List(ctx context.Context) ([]T, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]T, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []T); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call[T db.Entity] struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx
func (_e *MockRepository_Expecter[T]) List(ctx interface{}) *MockRepository_List_Call[T] {
	return &MockRepository_List_Call[T]{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRepository_List_Call[T]) Run(run func(ctx context.Context)) *MockRepository_List_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_List_Call[T]) Return(vs []T, err error) *MockRepository_List_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockRepository_List_Call[T]) RunAndReturn(run func(ctx context.Context) ([]T, error)) *MockRepository_List_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) Update(ctx context.Context, item *T) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *T) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call[T db.Entity] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx
//   - item
func (_e *MockRepository_Expecter[T]) Update(ctx interface{}, item interface{}) *MockRepository_Update_Call[T] {
	return &MockRepository_Update_Call[T]{Call: _e.mock.On("Update", ctx, item)}
}

func (_c *MockRepository_Update_Call[T]) Run(run func(ctx context.Context, item *T)) *MockRepository_Update_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*T))
	})
	return _c
}

func (_c *MockRepository_Update_Call[T]) Return(err error) *MockRepository_Update_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Update_Call[T]) RunAndReturn(run func(ctx context.Context, item *T) error) *MockRepository_Update_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) Upsert(ctx context.Context, item *T) (int64, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, *T) int64); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *T) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockRepository_Upsert_Call[T db.Entity] struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx
//   - item
func (_e *MockRepository_Expecter[T]) Upsert(ctx interface{}, item interface{}) *MockRepository_Upsert_Call[T] {
	return &MockRepository_Upsert_Call[T]{Call: _e.mock.On("Upsert", ctx, item)}
}

func (_c *MockRepository_Upsert_Call[T]) Run(run func(ctx context.Context, item *T)) *MockRepository_Upsert_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*T))
	})
	return _c
}

func (_c *MockRepository_Upsert_Call[T]) Return(rowsAffected int64, err error) *MockRepository_Upsert_Call[T] {
	_c.Call.Return(rowsAffected, err)
	return _c
}

func (_c *MockRepository_Upsert_Call[T]) RunAndReturn(run func(ctx context.Context, item *T) (int64, error)) *MockRepository_Upsert_Call[T] {
	_c.Call.Return(run)
	return _c
}
