// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nicolas-martin/dankfolio/backend/internal/model"

	time "time"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// CreateTrade provides a mock function with given fields: ctx, trade
func (_m *Store) CreateTrade(ctx context.Context, trade *model.Trade) error {
	ret := _m.Called(ctx, trade)

	if len(ret) == 0 {
		panic("no return value specified for CreateTrade")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Trade) error); ok {
		r0 = rf(ctx, trade)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCached provides a mock function with given fields: ctx, key
func (_m *Store) DeleteCached(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCached")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCoin provides a mock function with given fields: ctx, id
func (_m *Store) DeleteCoin(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCoin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTrade provides a mock function with given fields: ctx, id
func (_m *Store) DeleteTrade(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTrade")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCached provides a mock function with given fields: ctx, key
func (_m *Store) GetCached(ctx context.Context, key string) (interface{}, bool) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetCached")
	}

	var r0 interface{}
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) (interface{}, bool)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) interface{}); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetCoin provides a mock function with given fields: ctx, id
func (_m *Store) GetCoin(ctx context.Context, id string) (*model.Coin, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCoin")
	}

	var r0 *model.Coin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Coin, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Coin); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Coin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTrade provides a mock function with given fields: ctx, id
func (_m *Store) GetTrade(ctx context.Context, id string) (*model.Trade, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTrade")
	}

	var r0 *model.Trade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Trade, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Trade); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Trade)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCoins provides a mock function with given fields: ctx
func (_m *Store) ListCoins(ctx context.Context) ([]model.Coin, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCoins")
	}

	var r0 []model.Coin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Coin, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Coin); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Coin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTrades provides a mock function with given fields: ctx
func (_m *Store) ListTrades(ctx context.Context) ([]*model.Trade, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTrades")
	}

	var r0 []*model.Trade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Trade, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Trade); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Trade)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTrendingCoins provides a mock function with given fields: ctx
func (_m *Store) ListTrendingCoins(ctx context.Context) ([]model.Coin, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTrendingCoins")
	}

	var r0 []model.Coin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Coin, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Coin); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Coin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetCached provides a mock function with given fields: ctx, key, value, expiration
func (_m *Store) SetCached(ctx context.Context, key string, value interface{}, expiration time.Duration) error {
	ret := _m.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SetCached")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTrade provides a mock function with given fields: ctx, trade
func (_m *Store) UpdateTrade(ctx context.Context, trade *model.Trade) error {
	ret := _m.Called(ctx, trade)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTrade")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Trade) error); ok {
		r0 = rf(ctx, trade)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertCoin provides a mock function with given fields: ctx, coin
func (_m *Store) UpsertCoin(ctx context.Context, coin *model.Coin) error {
	ret := _m.Called(ctx, coin)

	if len(ret) == 0 {
		panic("no return value specified for UpsertCoin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Coin) error); ok {
		r0 = rf(ctx, coin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
