// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pricemocks

import (
	"context"

	"github.com/nicolas-martin/dankfolio/backend/internal/clients/birdeye"
	"github.com/nicolas-martin/dankfolio/backend/internal/service/price"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPriceServiceAPI creates a new instance of MockPriceServiceAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPriceServiceAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPriceServiceAPI {
	mock := &MockPriceServiceAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPriceServiceAPI is an autogenerated mock type for the PriceServiceAPI type
type MockPriceServiceAPI struct {
	mock.Mock
}

type MockPriceServiceAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPriceServiceAPI) EXPECT() *MockPriceServiceAPI_Expecter {
	return &MockPriceServiceAPI_Expecter{mock: &_m.Mock}
}

// GetCoinPrices provides a mock function for the type MockPriceServiceAPI
func (_mock *MockPriceServiceAPI) GetCoinPrices(ctx context.Context, tokenAddresses []string) (map[string]float64, error) {
	ret := _mock.Called(ctx, tokenAddresses)

	if len(ret) == 0 {
		panic("no return value specified for GetCoinPrices")
	}

	var r0 map[string]float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string]float64, error)); ok {
		return returnFunc(ctx, tokenAddresses)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string]float64); ok {
		r0 = returnFunc(ctx, tokenAddresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, tokenAddresses)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPriceServiceAPI_GetCoinPrices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoinPrices'
type MockPriceServiceAPI_GetCoinPrices_Call struct {
	*mock.Call
}

// GetCoinPrices is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenAddresses []string
func (_e *MockPriceServiceAPI_Expecter) GetCoinPrices(ctx interface{}, tokenAddresses interface{}) *MockPriceServiceAPI_GetCoinPrices_Call {
	return &MockPriceServiceAPI_GetCoinPrices_Call{Call: _e.mock.On("GetCoinPrices", ctx, tokenAddresses)}
}

func (_c *MockPriceServiceAPI_GetCoinPrices_Call) Run(run func(ctx context.Context, tokenAddresses []string)) *MockPriceServiceAPI_GetCoinPrices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPriceServiceAPI_GetCoinPrices_Call) Return(stringToFloat64 map[string]float64, err error) *MockPriceServiceAPI_GetCoinPrices_Call {
	_c.Call.Return(stringToFloat64, err)
	return _c
}

func (_c *MockPriceServiceAPI_GetCoinPrices_Call) RunAndReturn(run func(ctx context.Context, tokenAddresses []string) (map[string]float64, error)) *MockPriceServiceAPI_GetCoinPrices_Call {
	_c.Call.Return(run)
	return _c
}

// GetPriceHistory provides a mock function for the type MockPriceServiceAPI
func (_mock *MockPriceServiceAPI) GetPriceHistory(ctx context.Context, address string, config price.BackendTimeframeConfig, time string, addressType string) (*birdeye.PriceHistory, error) {
	ret := _mock.Called(ctx, address, config, time, addressType)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceHistory")
	}

	var r0 *birdeye.PriceHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, price.BackendTimeframeConfig, string, string) (*birdeye.PriceHistory, error)); ok {
		return returnFunc(ctx, address, config, time, addressType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, price.BackendTimeframeConfig, string, string) *birdeye.PriceHistory); ok {
		r0 = returnFunc(ctx, address, config, time, addressType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*birdeye.PriceHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, price.BackendTimeframeConfig, string, string) error); ok {
		r1 = returnFunc(ctx, address, config, time, addressType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPriceServiceAPI_GetPriceHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceHistory'
type MockPriceServiceAPI_GetPriceHistory_Call struct {
	*mock.Call
}

// GetPriceHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - config price.BackendTimeframeConfig
//   - time string
//   - addressType string
func (_e *MockPriceServiceAPI_Expecter) GetPriceHistory(ctx interface{}, address interface{}, config interface{}, time interface{}, addressType interface{}) *MockPriceServiceAPI_GetPriceHistory_Call {
	return &MockPriceServiceAPI_GetPriceHistory_Call{Call: _e.mock.On("GetPriceHistory", ctx, address, config, time, addressType)}
}

func (_c *MockPriceServiceAPI_GetPriceHistory_Call) Run(run func(ctx context.Context, address string, config price.BackendTimeframeConfig, time string, addressType string)) *MockPriceServiceAPI_GetPriceHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 price.BackendTimeframeConfig
		if args[2] != nil {
			arg2 = args[2].(price.BackendTimeframeConfig)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockPriceServiceAPI_GetPriceHistory_Call) Return(priceHistory *birdeye.PriceHistory, err error) *MockPriceServiceAPI_GetPriceHistory_Call {
	_c.Call.Return(priceHistory, err)
	return _c
}

func (_c *MockPriceServiceAPI_GetPriceHistory_Call) RunAndReturn(run func(ctx context.Context, address string, config price.BackendTimeframeConfig, time string, addressType string) (*birdeye.PriceHistory, error)) *MockPriceServiceAPI_GetPriceHistory_Call {
	_c.Call.Return(run)
	return _c
}
