// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pricemocks

import (
	"time"

	"github.com/nicolas-martin/dankfolio/backend/internal/clients/birdeye"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPriceHistoryCache creates a new instance of MockPriceHistoryCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPriceHistoryCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPriceHistoryCache {
	mock := &MockPriceHistoryCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPriceHistoryCache is an autogenerated mock type for the PriceHistoryCache type
type MockPriceHistoryCache struct {
	mock.Mock
}

type MockPriceHistoryCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPriceHistoryCache) EXPECT() *MockPriceHistoryCache_Expecter {
	return &MockPriceHistoryCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockPriceHistoryCache
func (_mock *MockPriceHistoryCache) Get(key string) (*birdeye.PriceHistory, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *birdeye.PriceHistory
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (*birdeye.PriceHistory, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *birdeye.PriceHistory); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*birdeye.PriceHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockPriceHistoryCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPriceHistoryCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockPriceHistoryCache_Expecter) Get(key interface{}) *MockPriceHistoryCache_Get_Call {
	return &MockPriceHistoryCache_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockPriceHistoryCache_Get_Call) Run(run func(key string)) *MockPriceHistoryCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPriceHistoryCache_Get_Call) Return(priceHistory *birdeye.PriceHistory, b bool) *MockPriceHistoryCache_Get_Call {
	_c.Call.Return(priceHistory, b)
	return _c
}

func (_c *MockPriceHistoryCache_Get_Call) RunAndReturn(run func(key string) (*birdeye.PriceHistory, bool)) *MockPriceHistoryCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockPriceHistoryCache
func (_mock *MockPriceHistoryCache) Set(key string, data *birdeye.PriceHistory, expiration time.Duration) {
	_mock.Called(key, data, expiration)
	return
}

// MockPriceHistoryCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockPriceHistoryCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - data *birdeye.PriceHistory
//   - expiration time.Duration
func (_e *MockPriceHistoryCache_Expecter) Set(key interface{}, data interface{}, expiration interface{}) *MockPriceHistoryCache_Set_Call {
	return &MockPriceHistoryCache_Set_Call{Call: _e.mock.On("Set", key, data, expiration)}
}

func (_c *MockPriceHistoryCache_Set_Call) Run(run func(key string, data *birdeye.PriceHistory, expiration time.Duration)) *MockPriceHistoryCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *birdeye.PriceHistory
		if args[1] != nil {
			arg1 = args[1].(*birdeye.PriceHistory)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPriceHistoryCache_Set_Call) Return() *MockPriceHistoryCache_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPriceHistoryCache_Set_Call) RunAndReturn(run func(key string, data *birdeye.PriceHistory, expiration time.Duration)) *MockPriceHistoryCache_Set_Call {
	_c.Run(run)
	return _c
}
