// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package priceMocks

import (
	"context"

	"github.com/nicolas-martin/dankfolio/backend/internal/clients/birdeye"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPriceServiceAPI creates a new instance of MockPriceServiceAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPriceServiceAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPriceServiceAPI {
	mock := &MockPriceServiceAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPriceServiceAPI is an autogenerated mock type for the PriceServiceAPI type
type MockPriceServiceAPI struct {
	mock.Mock
}

type MockPriceServiceAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPriceServiceAPI) EXPECT() *MockPriceServiceAPI_Expecter {
	return &MockPriceServiceAPI_Expecter{mock: &_m.Mock}
}

// GetCoinPrices provides a mock function for the type MockPriceServiceAPI
func (_mock *MockPriceServiceAPI) GetCoinPrices(ctx context.Context, tokenAddresses []string) (map[string]float64, error) {
	ret := _mock.Called(ctx, tokenAddresses)

	if len(ret) == 0 {
		panic("no return value specified for GetCoinPrices")
	}

	var r0 map[string]float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string]float64, error)); ok {
		return returnFunc(ctx, tokenAddresses)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string]float64); ok {
		r0 = returnFunc(ctx, tokenAddresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, tokenAddresses)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPriceServiceAPI_GetCoinPrices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoinPrices'
type MockPriceServiceAPI_GetCoinPrices_Call struct {
	*mock.Call
}

// GetCoinPrices is a helper method to define mock.On call
//   - ctx
//   - tokenAddresses
func (_e *MockPriceServiceAPI_Expecter) GetCoinPrices(ctx interface{}, tokenAddresses interface{}) *MockPriceServiceAPI_GetCoinPrices_Call {
	return &MockPriceServiceAPI_GetCoinPrices_Call{Call: _e.mock.On("GetCoinPrices", ctx, tokenAddresses)}
}

func (_c *MockPriceServiceAPI_GetCoinPrices_Call) Run(run func(ctx context.Context, tokenAddresses []string)) *MockPriceServiceAPI_GetCoinPrices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockPriceServiceAPI_GetCoinPrices_Call) Return(stringToFloat64 map[string]float64, err error) *MockPriceServiceAPI_GetCoinPrices_Call {
	_c.Call.Return(stringToFloat64, err)
	return _c
}

func (_c *MockPriceServiceAPI_GetCoinPrices_Call) RunAndReturn(run func(ctx context.Context, tokenAddresses []string) (map[string]float64, error)) *MockPriceServiceAPI_GetCoinPrices_Call {
	_c.Call.Return(run)
	return _c
}

// GetPriceHistory provides a mock function for the type MockPriceServiceAPI
func (_mock *MockPriceServiceAPI) GetPriceHistory(ctx context.Context, address string, historyType string, timeFromStr string, timeToStr string, addressType string) (*birdeye.PriceHistory, error) {
	ret := _mock.Called(ctx, address, historyType, timeFromStr, timeToStr, addressType)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceHistory")
	}

	var r0 *birdeye.PriceHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (*birdeye.PriceHistory, error)); ok {
		return returnFunc(ctx, address, historyType, timeFromStr, timeToStr, addressType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) *birdeye.PriceHistory); ok {
		r0 = returnFunc(ctx, address, historyType, timeFromStr, timeToStr, addressType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*birdeye.PriceHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, address, historyType, timeFromStr, timeToStr, addressType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPriceServiceAPI_GetPriceHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceHistory'
type MockPriceServiceAPI_GetPriceHistory_Call struct {
	*mock.Call
}

// GetPriceHistory is a helper method to define mock.On call
//   - ctx
//   - address
//   - historyType
//   - timeFromStr
//   - timeToStr
//   - addressType
func (_e *MockPriceServiceAPI_Expecter) GetPriceHistory(ctx interface{}, address interface{}, historyType interface{}, timeFromStr interface{}, timeToStr interface{}, addressType interface{}) *MockPriceServiceAPI_GetPriceHistory_Call {
	return &MockPriceServiceAPI_GetPriceHistory_Call{Call: _e.mock.On("GetPriceHistory", ctx, address, historyType, timeFromStr, timeToStr, addressType)}
}

func (_c *MockPriceServiceAPI_GetPriceHistory_Call) Run(run func(ctx context.Context, address string, historyType string, timeFromStr string, timeToStr string, addressType string)) *MockPriceServiceAPI_GetPriceHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockPriceServiceAPI_GetPriceHistory_Call) Return(priceHistory *birdeye.PriceHistory, err error) *MockPriceServiceAPI_GetPriceHistory_Call {
	_c.Call.Return(priceHistory, err)
	return _c
}

func (_c *MockPriceServiceAPI_GetPriceHistory_Call) RunAndReturn(run func(ctx context.Context, address string, historyType string, timeFromStr string, timeToStr string, addressType string) (*birdeye.PriceHistory, error)) *MockPriceServiceAPI_GetPriceHistory_Call {
	_c.Call.Return(run)
	return _c
}
