// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	birdeye "github.com/nicolas-martin/dankfolio/backend/internal/clients/birdeye"
	mock "github.com/stretchr/testify/mock"
)

// PriceServiceAPI is an autogenerated mock type for the PriceServiceAPI type
type PriceServiceAPI struct {
	mock.Mock
}

// GetCoinPrices provides a mock function with given fields: ctx, tokenAddresses
func (_m *PriceServiceAPI) GetCoinPrices(ctx context.Context, tokenAddresses []string) (map[string]float64, error) {
	ret := _m.Called(ctx, tokenAddresses)

	if len(ret) == 0 {
		panic("no return value specified for GetCoinPrices")
	}

	var r0 map[string]float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]float64, error)); ok {
		return rf(ctx, tokenAddresses)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]float64); ok {
		r0 = rf(ctx, tokenAddresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, tokenAddresses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPriceHistory provides a mock function with given fields: ctx, address, historyType, timeFromStr, timeToStr, addressType
func (_m *PriceServiceAPI) GetPriceHistory(ctx context.Context, address string, historyType string, timeFromStr string, timeToStr string, addressType string) (*birdeye.PriceHistory, error) {
	ret := _m.Called(ctx, address, historyType, timeFromStr, timeToStr, addressType)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceHistory")
	}

	var r0 *birdeye.PriceHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (*birdeye.PriceHistory, error)); ok {
		return rf(ctx, address, historyType, timeFromStr, timeToStr, addressType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) *birdeye.PriceHistory); ok {
		r0 = rf(ctx, address, historyType, timeFromStr, timeToStr, addressType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*birdeye.PriceHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, address, historyType, timeFromStr, timeToStr, addressType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPriceServiceAPI creates a new instance of PriceServiceAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceServiceAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceServiceAPI {
	mock := &PriceServiceAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
