import { StyleSheet } from 'react-native';
import { MD3Theme } from 'react-native-paper';

export const createStyles = (theme: MD3Theme) => StyleSheet.create({
	actionContainer: {
		padding: 20,
		paddingTop: 0,
	},
	cardLabel: {
		color: theme.colors.onSurfaceVariant,
		fontSize: 14,
		fontWeight: '600',
		letterSpacing: 0.5,
		marginBottom: 16,
		textTransform: 'uppercase',
	},
	container: {
		backgroundColor: theme.colors.background,
		flex: 1,
	},
	content: {
		padding: 20,
	},
	detailLabel: {
		color: theme.colors.onSurfaceVariant,
		fontSize: 14,
	},
	detailRow: {
		alignItems: 'center',
		flexDirection: 'row',
		justifyContent: 'space-between',
		marginBottom: 12,
	},
	detailValue: {
		color: theme.colors.onSurface,
		fontSize: 14,
		fontWeight: '600',
	},
	detailsCard: {
		backgroundColor: theme.colors.surfaceVariant,
		marginBottom: 24,
	},
	detailsContent: {
		paddingTop: 0,
	},
	detailsIcon: {
		alignItems: 'center',
		backgroundColor: theme.colors.primary,
		borderRadius: 12,
		height: 24,
		justifyContent: 'center',
		marginRight: 8,
		width: 24,
	},
	detailsTitle: {
		color: theme.colors.onSurface,
		fontSize: 16,
		fontWeight: '600',
	},
	errorContainer: {
		alignItems: 'center',
		backgroundColor: theme.colors.errorContainer,
		borderRadius: 12,
		flexDirection: 'row',
		marginBottom: 20,
		padding: 16,
	},
	errorIcon: {
		marginRight: 12,
	},
	errorText: {
		color: theme.colors.onErrorContainer,
		flex: 1,
		fontSize: 14,
	},
	exchangeRateLabel: {
		alignItems: 'center',
		color: theme.colors.onSurfaceVariant,
		flexDirection: 'row',
		fontSize: 14,
	},
	exchangeRateLabelText: {
		marginLeft: 4,
	},
	exchangeRateRow: {
		alignItems: 'center',
		borderTopColor: theme.colors.outline,
		borderTopWidth: 1,
		flexDirection: 'row',
		justifyContent: 'space-between',
		marginTop: 4,
		paddingTop: 12,
	},
	exchangeRateValue: {
		color: theme.colors.onSurface,
		fontSize: 16,
		fontWeight: '700',
	},
	header: { // Header Section
		alignItems: 'center',
		marginBottom: 32,
	},
	loadingContainer: {
		alignItems: 'center',
		flex: 1,
		justifyContent: 'center',
		padding: 20,
	},
	loadingText: {
		color: theme.colors.onSurfaceVariant,
		fontSize: 16,
		marginTop: 16,
		textAlign: 'center',
	},
	noWalletContainer: {
		alignItems: 'center',
		backgroundColor: theme.colors.background,
		flex: 1,
		justifyContent: 'center',
		padding: 20,
	},
	noWalletText: {
		color: theme.colors.onSurface,
		fontSize: 16,
		marginBottom: 20,
		textAlign: 'center',
	},
	refreshProgressBar: {
		borderRadius: 3,
		height: 6,
	},
	refreshProgressContainer: {
		backgroundColor: theme.colors.surfaceVariant,
		borderRadius: 12,
		marginBottom: 20,
		padding: 16,
	},
	refreshProgressHeader: {
		alignItems: 'center',
		flexDirection: 'row',
		marginBottom: 12,
	},
	refreshProgressIcon: {
		marginRight: 8,
	},
	refreshProgressLabel: {
		color: theme.colors.onSurfaceVariant,
		fontSize: 12,
		marginTop: 8,
		textAlign: 'center',
	},
	refreshProgressText: {
		color: theme.colors.onSurfaceVariant,
		fontSize: 14,
		fontWeight: '500',
	},
	scrollView: {
		flex: 1,
	},
	subtitle: {
		color: theme.colors.onSurfaceVariant,
		fontSize: 16,
		textAlign: 'center',
	},
	swapButton: {
		alignItems: 'center',
		backgroundColor: theme.colors.primary,
		borderRadius: 22,
		height: 44,
		justifyContent: 'center',
		width: 44,
	},
	swapButtonContainer: {
		alignItems: 'center',
		backgroundColor: theme.colors.background,
		borderColor: theme.colors.background,
		borderRadius: 28,
		borderWidth: 2,
		elevation: 8,
		height: 56,
		justifyContent: 'center',
		left: '50%',
		position: 'absolute',
		shadowColor: theme.colors.primary,
		shadowOffset: { width: 0, height: 0 },
		shadowOpacity: 0.3,
		shadowRadius: 8,
		top: -28,
		transform: [{ translateX: -28 }],
		width: 56,
		zIndex: 10,
	},
	title: { // Effective definition (was duplicate, using the latter one)
		color: theme.colors.onSurface,
		fontSize: 28,
		fontWeight: '700',
		marginBottom: 8,
		textAlign: 'center',
	},
	toCardContainerStyle: {
		marginTop: -8,
		position: 'relative',
	},
	tradeButton: {
		borderRadius: 16,
		elevation: 2,
		paddingVertical: 4,
		shadowColor: '#00FF9F',
		shadowOffset: { width: 0, height: 0 },
		shadowOpacity: 0.8,
		shadowRadius: 8,
	},
	tradeButtonContent: {
		paddingVertical: 12,
	},
	tradeButtonLabel: {
		fontSize: 18,
		fontWeight: '700',
	},
	tradeCard: {
		backgroundColor: theme.colors.surfaceVariant,
		borderRadius: 20,
		elevation: 2,
		marginBottom: 20,
		padding: 20,
		position: 'relative',
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 8,
	},
	tradeContainer: { // Trade Cards Container
		marginBottom: 24,
		position: 'relative',
	},
});
