import { StyleSheet } from 'react-native';
import { MD3Theme } from 'react-native-paper';

export const createStyles = (theme: MD3Theme) => StyleSheet.create({
	container: {
		backgroundColor: theme.colors.background,
		flex: 1,
	},
	section: {
		alignItems: 'center',
		padding: 20,
	},
	title: {
		color: theme.colors.onBackground,
		fontFamily: 'Manrope',
		fontSize: 28,
		fontWeight: '700',
		lineHeight: 35,
		textAlign: 'center',
	},
	subtitle: {
		color: theme.colors.onSurfaceVariant,
		fontFamily: 'Manrope',
		fontSize: 16,
		fontWeight: '400',
		lineHeight: 24,
		marginTop: 8,
		textAlign: 'center',
	},
	buttonRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		margin: 24,
	},
	actionButton: {
		alignItems: 'center',
		borderRadius: 24,
		height: 48,
		justifyContent: 'center',
		marginVertical: 6,
		width: '100%',
	},
	actionButtonYellow: {
		backgroundColor: theme.colors.primary,
	},
	actionButtonLight: {
		backgroundColor: theme.colors.surfaceVariant,
	},
	buttonText: {
		color: theme.colors.background,
		fontFamily: 'Manrope',
		fontSize: 16,
		fontWeight: '700',
	},
	termsText: {
		color: theme.colors.primary,
		fontFamily: 'Manrope',
		fontSize: 14,
		fontWeight: '400',
		marginTop: 24,
		paddingHorizontal: 20,
		textAlign: 'center',
	},
	termsContainer: {
		padding: 10,
		borderRadius: 8,
		marginTop: 24,
		borderBottomWidth: 1,
		borderBottomColor: theme.colors.primary,
		backgroundColor: 'transparent',
	},
	recoveryInput: {
		backgroundColor: theme.colors.surface,
		borderColor: theme.colors.outline,
		borderRadius: 12,
		borderWidth: 1,
		color: theme.colors.onSurface,
		fontSize: 16,
		margin: 16,
		padding: 15,
		width: '100%',
	},
	iconPlaceholder: {
		alignItems: 'center',
		backgroundColor: theme.colors.surfaceVariant,
		borderRadius: 24,
		height: 48,
		justifyContent: 'center',
		marginBottom: 16,
		width: 48,
	},
	loadingContainer: {
		alignItems: 'center',
		flex: 1,
		justifyContent: 'center',
		padding: 24,
	},
	spinnerContainer: {
		alignItems: 'center',
		height: 80,
		justifyContent: 'center',
		marginBottom: 24,
		width: 80,
	},
	walletInfoCard: {
		backgroundColor: theme.colors.surface,
		borderColor: theme.colors.outline,
		borderRadius: 16,
		borderWidth: 1,
		marginTop: 24,
		padding: 16,
		width: '100%',
	},
	walletInfoLabel: {
		color: theme.colors.primary,
		fontFamily: 'Manrope',
		fontSize: 14,
		fontWeight: '600',
		marginBottom: 8,
	},
	walletInfoValue: {
		backgroundColor: theme.colors.surfaceVariant,
		borderRadius: 8,
		color: theme.colors.onSurface,
		fontFamily: 'Manrope',
		fontSize: 14,
		fontWeight: '400',
		padding: 12,
	},
	mnemonicContainer: {
		backgroundColor: theme.colors.surfaceVariant,
		borderRadius: 12,
		marginTop: 16,
		padding: 16,
		width: '100%',
	},
	mnemonicGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		justifyContent: 'space-between',
		marginTop: 8,
	},
	mnemonicWord: {
		alignItems: 'center',
		flexDirection: 'row',
		marginBottom: 12,
		width: '48%',
	},
	wordNumber: {
		color: theme.colors.primary,
		fontFamily: 'Manrope',
		fontSize: 12,
		fontWeight: '600',
		width: 24,
	},
	debugText: {
		color: theme.colors.onSurfaceVariant,
		alignItems: 'center',
		marginBottom: 16,
		backgroundColor: theme.colors.surface,
		padding: 30,
		paddingLeft: 60
	},
	wordText: {
		color: theme.colors.onSurface,
		flex: 1,
		fontFamily: 'Manrope',
		fontSize: 14,
		fontWeight: '500',
	},
	centeredContent: {
		alignItems: 'center',
	},
	// Welcome screen specific styles
	welcomeContainer: {
		backgroundColor: theme.colors.background,
		flex: 1,
	},
	// New image container styles
	neonBarImageContainer: {
		height: 300,
		width: '100%',
		overflow: 'hidden',
	},
	neonBarImage: {
		width: '100%',
		height: '100%',
	},
	welcomeContent: {
		alignItems: 'center',
		backgroundColor: theme.colors.surface,
		borderTopLeftRadius: 24,
		borderTopRightRadius: 24,
		flex: 1,
		marginTop: -20,
		padding: 24,
	},
	buttonContainer: {
		marginTop: 24,
		width: '100%',
	},
	// Create wallet screen specific styles
	createContainer: {
		backgroundColor: theme.colors.background,
		flex: 1,
	},
	headerContainer: {
		alignItems: 'center',
		backgroundColor: theme.colors.surface,
		flexDirection: 'row',
		justifyContent: 'space-between',
		paddingBottom: 20,
		paddingHorizontal: 20,
		paddingTop: 60,
	},
	backButton: {
		alignItems: 'center',
		height: 40,
		justifyContent: 'center',
		width: 40,
	},
	backButtonText: {
		color: theme.colors.onSurface,
		fontSize: 24,
		fontWeight: '400',
	},
	headerTitle: {
		color: theme.colors.onSurface,
		fontFamily: 'Manrope',
		fontSize: 18,
		fontWeight: '600',
		textAlign: 'center',
	},
	headerSpacer: {
		width: 40,
	},
	createContent: {
		alignItems: 'center',
		flex: 1,
		paddingHorizontal: 24,
		paddingTop: 40,
	},
	createButtonContainer: {
		bottom: 40,
		left: 24,
		position: 'absolute',
		right: 24,
	},
	walletInfoSection: {
		marginBottom: 16,
	},
	walletInfoHeader: {
		alignItems: 'center',
		flexDirection: 'row',
		justifyContent: 'space-between',
		marginBottom: 8,
	},
	copyButton: {
		margin: 0,
		padding: 0,
	},
	confirmButtonContainer: {
		marginTop: 24,
		paddingBottom: 20,
		width: '100%',
	},
	// Import wallet screen specific styles
	importContainer: {
		flex: 1,
		backgroundColor: theme.colors.background,
	},
	importContent: {
		alignItems: 'center',
		flex: 1,
		paddingHorizontal: 24,
		paddingTop: 40,
	},
	importRecoveryInput: {
		borderRadius: 12,
		borderWidth: 1,
		borderColor: theme.colors.outline,
		color: theme.colors.onSurface,
		backgroundColor: theme.colors.surface,
		flex: 1,
		fontSize: 16,
		marginTop: 32,
		maxHeight: 300,
		padding: 16,
		width: '100%',
	},
	importButtonContainer: {
		bottom: 40,
		left: 24,
		position: 'absolute',
		right: 24,
	},
}); 
