import { StyleSheet } from 'react-native';
import { MD3Theme } from 'react-native-paper';

export const createStyles = (theme: MD3Theme) => StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: '#FFFFFF',
	},
	section: {
		padding: 20,
		alignItems: 'center',
	},
	title: {
		fontFamily: 'Manrope',
		fontWeight: '700',
		fontSize: 28,
		lineHeight: 35,
		color: '#1C170D',
		textAlign: 'center',
	},
	subtitle: {
		fontFamily: 'Manrope',
		fontWeight: '400',
		fontSize: 16,
		lineHeight: 24,
		color: '#1C170D',
		textAlign: 'center',
		marginTop: 8,
	},
	buttonRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		margin: 24,
	},
	actionButton: {
		flex: 1,
		borderRadius: 24,
		height: 48,
		alignItems: 'center',
		justifyContent: 'center',
		margin: 8,
	},
	actionButtonYellow: {
		backgroundColor: '#F5C754',
	},
	actionButtonLight: {
		backgroundColor: '#F2F0E8',
	},
	buttonText: {
		fontFamily: 'Manrope',
		fontWeight: '700',
		fontSize: 16,
		color: '#1C170D',
	},
	termsText: {
		fontFamily: 'Manrope',
		fontWeight: '400',
		fontSize: 14,
		color: '#9C854A',
		textAlign: 'center',
		marginTop: 24,
		paddingHorizontal: 20,
	},
	recoveryInput: {
		backgroundColor: '#FCFAF7',
		borderWidth: 1,
		borderColor: '#E8E0CF',
		borderRadius: 12,
		padding: 15,
		fontSize: 16,
		color: '#1C170D',
		margin: 16,
		width: '100%',
	},
	iconPlaceholder: {
		width: 48,
		height: 48,
		backgroundColor: '#F2F0E8',
		borderRadius: 24,
		alignItems: 'center',
		justifyContent: 'center',
		marginBottom: 16,
	},
	debugButtonContainer: {
		marginTop: 'auto',
		paddingBottom: 20,
		alignItems: 'center',
	},
	loadingContainer: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		padding: 24,
	},
	spinnerContainer: {
		width: 80,
		height: 80,
		alignItems: 'center',
		justifyContent: 'center',
		marginBottom: 24,
	},
	walletInfoCard: {
		backgroundColor: '#FCFAF7',
		borderWidth: 1,
		borderColor: '#E8E0CF',
		borderRadius: 16,
		padding: 16,
		width: '100%',
		marginTop: 24,
	},
	walletInfoLabel: {
		fontFamily: 'Manrope',
		fontWeight: '600',
		fontSize: 14,
		color: '#9C854A',
		marginBottom: 8,
	},
	walletInfoValue: {
		fontFamily: 'Manrope',
		fontWeight: '400',
		fontSize: 14,
		color: '#1C170D',
		padding: 12,
		backgroundColor: '#F2F0E8',
		borderRadius: 8,
	},
	mnemonicContainer: {
		backgroundColor: '#F2F0E8',
		borderRadius: 12,
		padding: 16,
		marginTop: 16,
		width: '100%',
	},
	mnemonicGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		justifyContent: 'space-between',
		marginTop: 8,
	},
	mnemonicWord: {
		flexDirection: 'row',
		width: '48%',
		marginBottom: 12,
		alignItems: 'center',
	},
	wordNumber: {
		fontFamily: 'Manrope',
		fontWeight: '600',
		fontSize: 12,
		color: '#9C854A',
		width: 24,
	},
	wordText: {
		fontFamily: 'Manrope',
		fontWeight: '500',
		fontSize: 14,
		color: '#1C170D',
		flex: 1,
	},
	centeredContent: {
		alignItems: 'center',
	},
}); 