import { StyleSheet } from 'react-native';
import { MD3Theme } from 'react-native-paper';

export const createStyles = (theme: MD3Theme) => StyleSheet.create({
	container: {
		backgroundColor: '#FFFFFF',
		flex: 1,
	},
	section: {
		alignItems: 'center',
		padding: 20,
	},
	title: {
		color: '#1C170D',
		fontFamily: 'Manrope',
		fontSize: 28,
		fontWeight: '700',
		lineHeight: 35,
		textAlign: 'center',
	},
	subtitle: {
		color: '#1C170D',
		fontFamily: 'Manrope',
		fontSize: 16,
		fontWeight: '400',
		lineHeight: 24,
		marginTop: 8,
		textAlign: 'center',
	},
	buttonRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		margin: 24,
	},
	actionButton: {
		alignItems: 'center',
		borderRadius: 24,
		height: 48,
		justifyContent: 'center',
		marginVertical: 6,
		width: '100%',
	},
	actionButtonYellow: {
		backgroundColor: '#F5C754',
	},
	actionButtonLight: {
		backgroundColor: '#F2F0E8',
	},
	buttonText: {
		color: '#1C170D',
		fontFamily: 'Manrope',
		fontSize: 16,
		fontWeight: '700',
	},
	termsText: {
		color: '#9C854A',
		fontFamily: 'Manrope',
		fontSize: 14,
		fontWeight: '400',
		marginTop: 24,
		paddingHorizontal: 20,
		textAlign: 'center',
	},
	recoveryInput: {
		backgroundColor: '#FCFAF7',
		borderColor: '#E8E0CF',
		borderRadius: 12,
		borderWidth: 1,
		color: '#1C170D',
		fontSize: 16,
		margin: 16,
		padding: 15,
		width: '100%',
	},
	iconPlaceholder: {
		alignItems: 'center',
		backgroundColor: '#F2F0E8',
		borderRadius: 24,
		height: 48,
		justifyContent: 'center',
		marginBottom: 16,
		width: 48,
	},
	debugButtonContainer: {
		alignItems: 'center',
		marginTop: 'auto',
		paddingBottom: 20,
	},
	loadingContainer: {
		alignItems: 'center',
		flex: 1,
		justifyContent: 'center',
		padding: 24,
	},
	spinnerContainer: {
		alignItems: 'center',
		height: 80,
		justifyContent: 'center',
		marginBottom: 24,
		width: 80,
	},
	walletInfoCard: {
		backgroundColor: '#FCFAF7',
		borderColor: '#E8E0CF',
		borderRadius: 16,
		borderWidth: 1,
		marginTop: 24,
		padding: 16,
		width: '100%',
	},
	walletInfoLabel: {
		color: '#9C854A',
		fontFamily: 'Manrope',
		fontSize: 14,
		fontWeight: '600',
		marginBottom: 8,
	},
	walletInfoValue: {
		backgroundColor: '#F2F0E8',
		borderRadius: 8,
		color: '#1C170D',
		fontFamily: 'Manrope',
		fontSize: 14,
		fontWeight: '400',
		padding: 12,
	},
	mnemonicContainer: {
		backgroundColor: '#F2F0E8',
		borderRadius: 12,
		marginTop: 16,
		padding: 16,
		width: '100%',
	},
	mnemonicGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		justifyContent: 'space-between',
		marginTop: 8,
	},
	mnemonicWord: {
		alignItems: 'center',
		flexDirection: 'row',
		marginBottom: 12,
		width: '48%',
	},
	wordNumber: {
		color: '#9C854A',
		fontFamily: 'Manrope',
		fontSize: 12,
		fontWeight: '600',
		width: 24,
	},
	wordText: {
		color: '#1C170D',
		flex: 1,
		fontFamily: 'Manrope',
		fontSize: 14,
		fontWeight: '500',
	},
	centeredContent: {
		alignItems: 'center',
	},
	// Welcome screen specific styles
	welcomeContainer: {
		backgroundColor: '#F5F1E8',
		flex: 1,
	},
	illustrationContainer: {
		alignItems: 'center',
		flex: 1,
		justifyContent: 'center',
		paddingBottom: 40,
		paddingTop: 60,
		position: 'relative',
	},
	frameContainer: {
		alignItems: 'center',
		backgroundColor: '#FFFFFF',
		borderRadius: 12,
		elevation: 4,
		height: 250,
		justifyContent: 'center',
		position: 'relative',
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 4,
		},
		shadowOpacity: 0.1,
		shadowRadius: 8,
		width: 200,
	},
	geometricShapes: {
		alignItems: 'center',
		height: '100%',
		justifyContent: 'center',
		position: 'absolute',
		width: '100%',
	},
	shape1: {
		backgroundColor: '#F5C754',
		borderRadius: 15,
		height: 30,
		left: 30,
		position: 'absolute',
		top: 40,
		width: 60,
	},
	shape2: {
		backgroundColor: '#E8B84A',
		borderRadius: 20,
		height: 40,
		position: 'absolute',
		right: 40,
		top: 80,
		width: 40,
	},
	shape3: {
		backgroundColor: '#D4A843',
		borderRadius: 12,
		bottom: 60,
		height: 25,
		left: 50,
		position: 'absolute',
		width: 50,
	},
	plantContainer: {
		position: 'absolute',
		right: -20,
		top: 20,
		zIndex: 2,
	},
	plant: {
		backgroundColor: '#4A7C59',
		borderRadius: 20,
		height: 80,
		width: 40,
	},
	vaseContainer: {
		bottom: 0,
		left: -30,
		position: 'absolute',
		zIndex: 2,
	},
	vase: {
		backgroundColor: '#E8E0CF',
		borderRadius: 30,
		height: 40,
		width: 60,
	},
	welcomeContent: {
		alignItems: 'center',
		paddingBottom: 40,
		paddingHorizontal: 24,
	},
	buttonContainer: {
		gap: 12,
		marginTop: 32,
		width: '100%',
	},
	// Create wallet screen specific styles
	createContainer: {
		backgroundColor: '#FFFFFF',
		flex: 1,
	},
	headerContainer: {
		alignItems: 'center',
		backgroundColor: '#FFFFFF',
		flexDirection: 'row',
		justifyContent: 'space-between',
		paddingBottom: 20,
		paddingHorizontal: 20,
		paddingTop: 60,
	},
	backButton: {
		alignItems: 'center',
		height: 40,
		justifyContent: 'center',
		width: 40,
	},
	backButtonText: {
		color: '#1C170D',
		fontSize: 24,
		fontWeight: '400',
	},
	headerTitle: {
		color: '#1C170D',
		fontFamily: 'Manrope',
		fontSize: 18,
		fontWeight: '600',
		textAlign: 'center',
	},
	headerSpacer: {
		width: 40,
	},
	createContent: {
		alignItems: 'center',
		flex: 1,
		paddingHorizontal: 24,
		paddingTop: 40,
	},
	createButtonContainer: {
		bottom: 40,
		left: 24,
		position: 'absolute',
		right: 24,
	},
	walletInfoSection: {
		marginBottom: 16,
	},
	walletInfoHeader: {
		alignItems: 'center',
		flexDirection: 'row',
		justifyContent: 'space-between',
		marginBottom: 8,
	},
	copyButton: {
		margin: 0,
		padding: 0,
	},
	confirmButtonContainer: {
		marginTop: 24,
		paddingBottom: 20,
		width: '100%',
	},
	// Import wallet screen specific styles
	importContainer: {
		backgroundColor: '#FFFFFF',
		flex: 1,
	},
	importContent: {
		alignItems: 'center',
		flex: 1,
		paddingHorizontal: 24,
		paddingTop: 40,
	},
	importRecoveryInput: {
		backgroundColor: '#FCFAF7',
		borderColor: '#E8E0CF',
		borderRadius: 12,
		borderWidth: 1,
		color: '#1C170D',
		flex: 1,
		fontSize: 16,
		marginTop: 32,
		maxHeight: 300,
		padding: 16,
		width: '100%',
	},
	importButtonContainer: {
		bottom: 40,
		left: 24,
		position: 'absolute',
		right: 24,
	},
}); 