// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nicolas-martin/dankfolio/backend/internal/clients/jupiter"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientAPI creates a new instance of MockClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientAPI {
	mock := &MockClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientAPI is an autogenerated mock type for the ClientAPI type
type MockClientAPI struct {
	mock.Mock
}

type MockClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientAPI) EXPECT() *MockClientAPI_Expecter {
	return &MockClientAPI_Expecter{mock: &_m.Mock}
}

// GetQuote provides a mock function for the type MockClientAPI
func (_mock *MockClientAPI) GetQuote(params jupiter.QuoteParams) (*jupiter.QuoteResponse, error) {
	ret := _mock.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetQuote")
	}

	var r0 *jupiter.QuoteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(jupiter.QuoteParams) (*jupiter.QuoteResponse, error)); ok {
		return returnFunc(params)
	}
	if returnFunc, ok := ret.Get(0).(func(jupiter.QuoteParams) *jupiter.QuoteResponse); ok {
		r0 = returnFunc(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jupiter.QuoteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(jupiter.QuoteParams) error); ok {
		r1 = returnFunc(params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAPI_GetQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuote'
type MockClientAPI_GetQuote_Call struct {
	*mock.Call
}

// GetQuote is a helper method to define mock.On call
//   - params
func (_e *MockClientAPI_Expecter) GetQuote(params interface{}) *MockClientAPI_GetQuote_Call {
	return &MockClientAPI_GetQuote_Call{Call: _e.mock.On("GetQuote", params)}
}

func (_c *MockClientAPI_GetQuote_Call) Run(run func(params jupiter.QuoteParams)) *MockClientAPI_GetQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(jupiter.QuoteParams))
	})
	return _c
}

func (_c *MockClientAPI_GetQuote_Call) Return(quoteResponse *jupiter.QuoteResponse, err error) *MockClientAPI_GetQuote_Call {
	_c.Call.Return(quoteResponse, err)
	return _c
}

func (_c *MockClientAPI_GetQuote_Call) RunAndReturn(run func(params jupiter.QuoteParams) (*jupiter.QuoteResponse, error)) *MockClientAPI_GetQuote_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenInfo provides a mock function for the type MockClientAPI
func (_mock *MockClientAPI) GetTokenInfo(tokenAddress string) (*jupiter.TokenInfoResponse, error) {
	ret := _mock.Called(tokenAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenInfo")
	}

	var r0 *jupiter.TokenInfoResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*jupiter.TokenInfoResponse, error)); ok {
		return returnFunc(tokenAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *jupiter.TokenInfoResponse); ok {
		r0 = returnFunc(tokenAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jupiter.TokenInfoResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAPI_GetTokenInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenInfo'
type MockClientAPI_GetTokenInfo_Call struct {
	*mock.Call
}

// GetTokenInfo is a helper method to define mock.On call
//   - tokenAddress
func (_e *MockClientAPI_Expecter) GetTokenInfo(tokenAddress interface{}) *MockClientAPI_GetTokenInfo_Call {
	return &MockClientAPI_GetTokenInfo_Call{Call: _e.mock.On("GetTokenInfo", tokenAddress)}
}

func (_c *MockClientAPI_GetTokenInfo_Call) Run(run func(tokenAddress string)) *MockClientAPI_GetTokenInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClientAPI_GetTokenInfo_Call) Return(tokenInfoResponse *jupiter.TokenInfoResponse, err error) *MockClientAPI_GetTokenInfo_Call {
	_c.Call.Return(tokenInfoResponse, err)
	return _c
}

func (_c *MockClientAPI_GetTokenInfo_Call) RunAndReturn(run func(tokenAddress string) (*jupiter.TokenInfoResponse, error)) *MockClientAPI_GetTokenInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenPrices provides a mock function for the type MockClientAPI
func (_mock *MockClientAPI) GetTokenPrices(tokenAddresses []string) (map[string]float64, error) {
	ret := _mock.Called(tokenAddresses)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenPrices")
	}

	var r0 map[string]float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) (map[string]float64, error)); ok {
		return returnFunc(tokenAddresses)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) map[string]float64); ok {
		r0 = returnFunc(tokenAddresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(tokenAddresses)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAPI_GetTokenPrices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenPrices'
type MockClientAPI_GetTokenPrices_Call struct {
	*mock.Call
}

// GetTokenPrices is a helper method to define mock.On call
//   - tokenAddresses
func (_e *MockClientAPI_Expecter) GetTokenPrices(tokenAddresses interface{}) *MockClientAPI_GetTokenPrices_Call {
	return &MockClientAPI_GetTokenPrices_Call{Call: _e.mock.On("GetTokenPrices", tokenAddresses)}
}

func (_c *MockClientAPI_GetTokenPrices_Call) Run(run func(tokenAddresses []string)) *MockClientAPI_GetTokenPrices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockClientAPI_GetTokenPrices_Call) Return(stringToFloat64 map[string]float64, err error) *MockClientAPI_GetTokenPrices_Call {
	_c.Call.Return(stringToFloat64, err)
	return _c
}

func (_c *MockClientAPI_GetTokenPrices_Call) RunAndReturn(run func(tokenAddresses []string) (map[string]float64, error)) *MockClientAPI_GetTokenPrices_Call {
	_c.Call.Return(run)
	return _c
}
