// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	jupiter "github.com/nicolas-martin/dankfolio/backend/internal/clients/jupiter"
	mock "github.com/stretchr/testify/mock"
	solanago "github.com/gagliardetto/solana-go"
)

// ClientAPI is an autogenerated mock type for the ClientAPI type
type ClientAPI struct {
	mock.Mock
}

// CreateSwapTransaction provides a mock function with given fields: ctx, quoteResp, userPublicKey
func (_m *ClientAPI) CreateSwapTransaction(ctx context.Context, quoteResp []byte, userPublicKey solanago.PublicKey) (string, error) {
	ret := _m.Called(ctx, quoteResp, userPublicKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateSwapTransaction")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, solanago.PublicKey) (string, error)); ok {
		return rf(ctx, quoteResp, userPublicKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, solanago.PublicKey) string); ok {
		r0 = rf(ctx, quoteResp, userPublicKey)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, solanago.PublicKey) error); ok {
		r1 = rf(ctx, quoteResp, userPublicKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCoins provides a mock function with given fields: ctx
func (_m *ClientAPI) GetAllCoins(ctx context.Context) (*jupiter.CoinListResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCoins")
	}

	var r0 *jupiter.CoinListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*jupiter.CoinListResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *jupiter.CoinListResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jupiter.CoinListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCoinInfo provides a mock function with given fields: ctx, tokenAddress
func (_m *ClientAPI) GetCoinInfo(ctx context.Context, tokenAddress string) (*jupiter.CoinListInfo, error) {
	ret := _m.Called(ctx, tokenAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetCoinInfo")
	}

	var r0 *jupiter.CoinListInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*jupiter.CoinListInfo, error)); ok {
		return rf(ctx, tokenAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *jupiter.CoinListInfo); ok {
		r0 = rf(ctx, tokenAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jupiter.CoinListInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCoinPrices provides a mock function with given fields: ctx, tokenAddresses
func (_m *ClientAPI) GetCoinPrices(ctx context.Context, tokenAddresses []string) (map[string]float64, error) {
	ret := _m.Called(ctx, tokenAddresses)

	if len(ret) == 0 {
		panic("no return value specified for GetCoinPrices")
	}

	var r0 map[string]float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]float64, error)); ok {
		return rf(ctx, tokenAddresses)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]float64); ok {
		r0 = rf(ctx, tokenAddresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, tokenAddresses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQuote provides a mock function with given fields: ctx, params
func (_m *ClientAPI) GetQuote(ctx context.Context, params jupiter.QuoteParams) (*jupiter.QuoteResponse, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetQuote")
	}

	var r0 *jupiter.QuoteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, jupiter.QuoteParams) (*jupiter.QuoteResponse, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, jupiter.QuoteParams) *jupiter.QuoteResponse); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jupiter.QuoteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, jupiter.QuoteParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRequest provides a mock function with given fields: ctx, url, target
func (_m *ClientAPI) GetRequest(ctx context.Context, url string, target interface{}) error {
	ret := _m.Called(ctx, url, target)

	if len(ret) == 0 {
		panic("no return value specified for GetRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, url, target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PostRequest provides a mock function with given fields: ctx, url, requestBody, target
func (_m *ClientAPI) PostRequest(ctx context.Context, url string, requestBody interface{}, target interface{}) error {
	ret := _m.Called(ctx, url, requestBody, target)

	if len(ret) == 0 {
		panic("no return value specified for PostRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, interface{}) error); ok {
		r0 = rf(ctx, url, requestBody, target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClientAPI creates a new instance of ClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientAPI {
	mock := &ClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
