// Code generated by mockery v2.53.4. DO NOT EDIT.

package jupitermocks

import (
	context "context"

	jupiter "github.com/nicolas-martin/dankfolio/backend/internal/clients/jupiter"
	mock "github.com/stretchr/testify/mock"

	solana "github.com/gagliardetto/solana-go"
)

// MockClientAPI is an autogenerated mock type for the ClientAPI type
type MockClientAPI struct {
	mock.Mock
}

type MockClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientAPI) EXPECT() *MockClientAPI_Expecter {
	return &MockClientAPI_Expecter{mock: &_m.Mock}
}

// CreateSwapTransaction provides a mock function with given fields: ctx, quoteResp, userPublicKey, feeAccount
func (_m *MockClientAPI) CreateSwapTransaction(ctx context.Context, quoteResp []byte, userPublicKey solana.PublicKey, feeAccount string) (string, error) {
	ret := _m.Called(ctx, quoteResp, userPublicKey, feeAccount)

	if len(ret) == 0 {
		panic("no return value specified for CreateSwapTransaction")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, solana.PublicKey, string) (string, error)); ok {
		return rf(ctx, quoteResp, userPublicKey, feeAccount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, solana.PublicKey, string) string); ok {
		r0 = rf(ctx, quoteResp, userPublicKey, feeAccount)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, solana.PublicKey, string) error); ok {
		r1 = rf(ctx, quoteResp, userPublicKey, feeAccount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_CreateSwapTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSwapTransaction'
type MockClientAPI_CreateSwapTransaction_Call struct {
	*mock.Call
}

// CreateSwapTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - quoteResp []byte
//   - userPublicKey solana.PublicKey
//   - feeAccount string
func (_e *MockClientAPI_Expecter) CreateSwapTransaction(ctx interface{}, quoteResp interface{}, userPublicKey interface{}, feeAccount interface{}) *MockClientAPI_CreateSwapTransaction_Call {
	return &MockClientAPI_CreateSwapTransaction_Call{Call: _e.mock.On("CreateSwapTransaction", ctx, quoteResp, userPublicKey, feeAccount)}
}

func (_c *MockClientAPI_CreateSwapTransaction_Call) Run(run func(ctx context.Context, quoteResp []byte, userPublicKey solana.PublicKey, feeAccount string)) *MockClientAPI_CreateSwapTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(solana.PublicKey), args[3].(string))
	})
	return _c
}

func (_c *MockClientAPI_CreateSwapTransaction_Call) Return(_a0 string, _a1 error) *MockClientAPI_CreateSwapTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_CreateSwapTransaction_Call) RunAndReturn(run func(context.Context, []byte, solana.PublicKey, string) (string, error)) *MockClientAPI_CreateSwapTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCoins provides a mock function with given fields: ctx
func (_m *MockClientAPI) GetAllCoins(ctx context.Context) (*jupiter.CoinListResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCoins")
	}

	var r0 *jupiter.CoinListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*jupiter.CoinListResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *jupiter.CoinListResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jupiter.CoinListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_GetAllCoins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCoins'
type MockClientAPI_GetAllCoins_Call struct {
	*mock.Call
}

// GetAllCoins is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientAPI_Expecter) GetAllCoins(ctx interface{}) *MockClientAPI_GetAllCoins_Call {
	return &MockClientAPI_GetAllCoins_Call{Call: _e.mock.On("GetAllCoins", ctx)}
}

func (_c *MockClientAPI_GetAllCoins_Call) Run(run func(ctx context.Context)) *MockClientAPI_GetAllCoins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClientAPI_GetAllCoins_Call) Return(_a0 *jupiter.CoinListResponse, _a1 error) *MockClientAPI_GetAllCoins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_GetAllCoins_Call) RunAndReturn(run func(context.Context) (*jupiter.CoinListResponse, error)) *MockClientAPI_GetAllCoins_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoinInfo provides a mock function with given fields: ctx, address
func (_m *MockClientAPI) GetCoinInfo(ctx context.Context, address string) (*jupiter.CoinListInfo, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetCoinInfo")
	}

	var r0 *jupiter.CoinListInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*jupiter.CoinListInfo, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *jupiter.CoinListInfo); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jupiter.CoinListInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_GetCoinInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoinInfo'
type MockClientAPI_GetCoinInfo_Call struct {
	*mock.Call
}

// GetCoinInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
func (_e *MockClientAPI_Expecter) GetCoinInfo(ctx interface{}, address interface{}) *MockClientAPI_GetCoinInfo_Call {
	return &MockClientAPI_GetCoinInfo_Call{Call: _e.mock.On("GetCoinInfo", ctx, address)}
}

func (_c *MockClientAPI_GetCoinInfo_Call) Run(run func(ctx context.Context, address string)) *MockClientAPI_GetCoinInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClientAPI_GetCoinInfo_Call) Return(_a0 *jupiter.CoinListInfo, _a1 error) *MockClientAPI_GetCoinInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_GetCoinInfo_Call) RunAndReturn(run func(context.Context, string) (*jupiter.CoinListInfo, error)) *MockClientAPI_GetCoinInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoinPrices provides a mock function with given fields: ctx, addresses
func (_m *MockClientAPI) GetCoinPrices(ctx context.Context, addresses []string) (map[string]float64, error) {
	ret := _m.Called(ctx, addresses)

	if len(ret) == 0 {
		panic("no return value specified for GetCoinPrices")
	}

	var r0 map[string]float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]float64, error)); ok {
		return rf(ctx, addresses)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]float64); ok {
		r0 = rf(ctx, addresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, addresses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_GetCoinPrices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoinPrices'
type MockClientAPI_GetCoinPrices_Call struct {
	*mock.Call
}

// GetCoinPrices is a helper method to define mock.On call
//   - ctx context.Context
//   - addresses []string
func (_e *MockClientAPI_Expecter) GetCoinPrices(ctx interface{}, addresses interface{}) *MockClientAPI_GetCoinPrices_Call {
	return &MockClientAPI_GetCoinPrices_Call{Call: _e.mock.On("GetCoinPrices", ctx, addresses)}
}

func (_c *MockClientAPI_GetCoinPrices_Call) Run(run func(ctx context.Context, addresses []string)) *MockClientAPI_GetCoinPrices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockClientAPI_GetCoinPrices_Call) Return(_a0 map[string]float64, _a1 error) *MockClientAPI_GetCoinPrices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_GetCoinPrices_Call) RunAndReturn(run func(context.Context, []string) (map[string]float64, error)) *MockClientAPI_GetCoinPrices_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewCoins provides a mock function with given fields: ctx, params
func (_m *MockClientAPI) GetNewCoins(ctx context.Context, params *jupiter.NewCoinsParams) ([]*jupiter.NewTokenInfo, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetNewCoins")
	}

	var r0 []*jupiter.NewTokenInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *jupiter.NewCoinsParams) ([]*jupiter.NewTokenInfo, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *jupiter.NewCoinsParams) []*jupiter.NewTokenInfo); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*jupiter.NewTokenInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *jupiter.NewCoinsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_GetNewCoins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewCoins'
type MockClientAPI_GetNewCoins_Call struct {
	*mock.Call
}

// GetNewCoins is a helper method to define mock.On call
//   - ctx context.Context
//   - params *jupiter.NewCoinsParams
func (_e *MockClientAPI_Expecter) GetNewCoins(ctx interface{}, params interface{}) *MockClientAPI_GetNewCoins_Call {
	return &MockClientAPI_GetNewCoins_Call{Call: _e.mock.On("GetNewCoins", ctx, params)}
}

func (_c *MockClientAPI_GetNewCoins_Call) Run(run func(ctx context.Context, params *jupiter.NewCoinsParams)) *MockClientAPI_GetNewCoins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*jupiter.NewCoinsParams))
	})
	return _c
}

func (_c *MockClientAPI_GetNewCoins_Call) Return(_a0 []*jupiter.NewTokenInfo, _a1 error) *MockClientAPI_GetNewCoins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_GetNewCoins_Call) RunAndReturn(run func(context.Context, *jupiter.NewCoinsParams) ([]*jupiter.NewTokenInfo, error)) *MockClientAPI_GetNewCoins_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuote provides a mock function with given fields: ctx, params
func (_m *MockClientAPI) GetQuote(ctx context.Context, params jupiter.QuoteParams) (*jupiter.QuoteResponse, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetQuote")
	}

	var r0 *jupiter.QuoteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, jupiter.QuoteParams) (*jupiter.QuoteResponse, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, jupiter.QuoteParams) *jupiter.QuoteResponse); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jupiter.QuoteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, jupiter.QuoteParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_GetQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuote'
type MockClientAPI_GetQuote_Call struct {
	*mock.Call
}

// GetQuote is a helper method to define mock.On call
//   - ctx context.Context
//   - params jupiter.QuoteParams
func (_e *MockClientAPI_Expecter) GetQuote(ctx interface{}, params interface{}) *MockClientAPI_GetQuote_Call {
	return &MockClientAPI_GetQuote_Call{Call: _e.mock.On("GetQuote", ctx, params)}
}

func (_c *MockClientAPI_GetQuote_Call) Run(run func(ctx context.Context, params jupiter.QuoteParams)) *MockClientAPI_GetQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(jupiter.QuoteParams))
	})
	return _c
}

func (_c *MockClientAPI_GetQuote_Call) Return(_a0 *jupiter.QuoteResponse, _a1 error) *MockClientAPI_GetQuote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_GetQuote_Call) RunAndReturn(run func(context.Context, jupiter.QuoteParams) (*jupiter.QuoteResponse, error)) *MockClientAPI_GetQuote_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientAPI creates a new instance of MockClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientAPI {
	mock := &MockClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
