// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	jupiter "github.com/nicolas-martin/dankfolio/backend/internal/clients/jupiter"
	mock "github.com/stretchr/testify/mock"
)

// ClientAPI is an autogenerated mock type for the ClientAPI type
type ClientAPI struct {
	mock.Mock
}

// GetQuote provides a mock function with given fields: params
func (_m *ClientAPI) GetQuote(params jupiter.QuoteParams) (*jupiter.QuoteResponse, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetQuote")
	}

	var r0 *jupiter.QuoteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(jupiter.QuoteParams) (*jupiter.QuoteResponse, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(jupiter.QuoteParams) *jupiter.QuoteResponse); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jupiter.QuoteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(jupiter.QuoteParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTokenInfo provides a mock function with given fields: tokenAddress
func (_m *ClientAPI) GetTokenInfo(tokenAddress string) (*jupiter.TokenInfoResponse, error) {
	ret := _m.Called(tokenAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenInfo")
	}

	var r0 *jupiter.TokenInfoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*jupiter.TokenInfoResponse, error)); ok {
		return rf(tokenAddress)
	}
	if rf, ok := ret.Get(0).(func(string) *jupiter.TokenInfoResponse); ok {
		r0 = rf(tokenAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jupiter.TokenInfoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTokenPrices provides a mock function with given fields: tokenAddresses
func (_m *ClientAPI) GetTokenPrices(tokenAddresses []string) (map[string]float64, error) {
	ret := _m.Called(tokenAddresses)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenPrices")
	}

	var r0 map[string]float64
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) (map[string]float64, error)); ok {
		return rf(tokenAddresses)
	}
	if rf, ok := ret.Get(0).(func([]string) map[string]float64); ok {
		r0 = rf(tokenAddresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(tokenAddresses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientAPI creates a new instance of ClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientAPI {
	mock := &ClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
