// Code generated by mockery v2.53.4. DO NOT EDIT.

package price

import (
	birdeye "github.com/nicolas-martin/dankfolio/backend/internal/clients/birdeye"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockPriceHistoryCache is an autogenerated mock type for the PriceHistoryCache type
type MockPriceHistoryCache struct {
	mock.Mock
}

type MockPriceHistoryCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPriceHistoryCache) EXPECT() *MockPriceHistoryCache_Expecter {
	return &MockPriceHistoryCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *MockPriceHistoryCache) Get(key string) (*birdeye.PriceHistory, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *birdeye.PriceHistory
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*birdeye.PriceHistory, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *birdeye.PriceHistory); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*birdeye.PriceHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockPriceHistoryCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPriceHistoryCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockPriceHistoryCache_Expecter) Get(key interface{}) *MockPriceHistoryCache_Get_Call {
	return &MockPriceHistoryCache_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockPriceHistoryCache_Get_Call) Run(run func(key string)) *MockPriceHistoryCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPriceHistoryCache_Get_Call) Return(_a0 *birdeye.PriceHistory, _a1 bool) *MockPriceHistoryCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPriceHistoryCache_Get_Call) RunAndReturn(run func(string) (*birdeye.PriceHistory, bool)) *MockPriceHistoryCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, data, expiration
func (_m *MockPriceHistoryCache) Set(key string, data *birdeye.PriceHistory, expiration time.Duration) {
	_m.Called(key, data, expiration)
}

// MockPriceHistoryCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockPriceHistoryCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - data *birdeye.PriceHistory
//   - expiration time.Duration
func (_e *MockPriceHistoryCache_Expecter) Set(key interface{}, data interface{}, expiration interface{}) *MockPriceHistoryCache_Set_Call {
	return &MockPriceHistoryCache_Set_Call{Call: _e.mock.On("Set", key, data, expiration)}
}

func (_c *MockPriceHistoryCache_Set_Call) Run(run func(key string, data *birdeye.PriceHistory, expiration time.Duration)) *MockPriceHistoryCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*birdeye.PriceHistory), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockPriceHistoryCache_Set_Call) Return() *MockPriceHistoryCache_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPriceHistoryCache_Set_Call) RunAndReturn(run func(string, *birdeye.PriceHistory, time.Duration)) *MockPriceHistoryCache_Set_Call {
	_c.Run(run)
	return _c
}

// NewMockPriceHistoryCache creates a new instance of MockPriceHistoryCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPriceHistoryCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPriceHistoryCache {
	mock := &MockPriceHistoryCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
