// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package birdeyeMocks

import (
	"context"

	"github.com/nicolas-martin/dankfolio/backend/internal/clients/birdeye"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientAPI creates a new instance of MockClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientAPI {
	mock := &MockClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientAPI is an autogenerated mock type for the ClientAPI type
type MockClientAPI struct {
	mock.Mock
}

type MockClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientAPI) EXPECT() *MockClientAPI_Expecter {
	return &MockClientAPI_Expecter{mock: &_m.Mock}
}

// GetPriceHistory provides a mock function for the type MockClientAPI
func (_mock *MockClientAPI) GetPriceHistory(ctx context.Context, params birdeye.PriceHistoryParams) (*birdeye.PriceHistory, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceHistory")
	}

	var r0 *birdeye.PriceHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, birdeye.PriceHistoryParams) (*birdeye.PriceHistory, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, birdeye.PriceHistoryParams) *birdeye.PriceHistory); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*birdeye.PriceHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, birdeye.PriceHistoryParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAPI_GetPriceHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceHistory'
type MockClientAPI_GetPriceHistory_Call struct {
	*mock.Call
}

// GetPriceHistory is a helper method to define mock.On call
//   - ctx
//   - params
func (_e *MockClientAPI_Expecter) GetPriceHistory(ctx interface{}, params interface{}) *MockClientAPI_GetPriceHistory_Call {
	return &MockClientAPI_GetPriceHistory_Call{Call: _e.mock.On("GetPriceHistory", ctx, params)}
}

func (_c *MockClientAPI_GetPriceHistory_Call) Run(run func(ctx context.Context, params birdeye.PriceHistoryParams)) *MockClientAPI_GetPriceHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(birdeye.PriceHistoryParams))
	})
	return _c
}

func (_c *MockClientAPI_GetPriceHistory_Call) Return(priceHistory *birdeye.PriceHistory, err error) *MockClientAPI_GetPriceHistory_Call {
	_c.Call.Return(priceHistory, err)
	return _c
}

func (_c *MockClientAPI_GetPriceHistory_Call) RunAndReturn(run func(ctx context.Context, params birdeye.PriceHistoryParams) (*birdeye.PriceHistory, error)) *MockClientAPI_GetPriceHistory_Call {
	_c.Call.Return(run)
	return _c
}
