// Code generated by mockery v2.53.4. DO NOT EDIT.

package birdeyemocks

import (
	context "context"

	birdeye "github.com/nicolas-martin/dankfolio/backend/internal/clients/birdeye"

	mock "github.com/stretchr/testify/mock"
)

// MockClientAPI is an autogenerated mock type for the ClientAPI type
type MockClientAPI struct {
	mock.Mock
}

type MockClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientAPI) EXPECT() *MockClientAPI_Expecter {
	return &MockClientAPI_Expecter{mock: &_m.Mock}
}

// GetPriceHistory provides a mock function with given fields: ctx, params
func (_m *MockClientAPI) GetPriceHistory(ctx context.Context, params birdeye.PriceHistoryParams) (*birdeye.PriceHistory, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceHistory")
	}

	var r0 *birdeye.PriceHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, birdeye.PriceHistoryParams) (*birdeye.PriceHistory, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, birdeye.PriceHistoryParams) *birdeye.PriceHistory); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*birdeye.PriceHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, birdeye.PriceHistoryParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_GetPriceHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceHistory'
type MockClientAPI_GetPriceHistory_Call struct {
	*mock.Call
}

// GetPriceHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - params birdeye.PriceHistoryParams
func (_e *MockClientAPI_Expecter) GetPriceHistory(ctx interface{}, params interface{}) *MockClientAPI_GetPriceHistory_Call {
	return &MockClientAPI_GetPriceHistory_Call{Call: _e.mock.On("GetPriceHistory", ctx, params)}
}

func (_c *MockClientAPI_GetPriceHistory_Call) Run(run func(ctx context.Context, params birdeye.PriceHistoryParams)) *MockClientAPI_GetPriceHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(birdeye.PriceHistoryParams))
	})
	return _c
}

func (_c *MockClientAPI_GetPriceHistory_Call) Return(_a0 *birdeye.PriceHistory, _a1 error) *MockClientAPI_GetPriceHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_GetPriceHistory_Call) RunAndReturn(run func(context.Context, birdeye.PriceHistoryParams) (*birdeye.PriceHistory, error)) *MockClientAPI_GetPriceHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrendingTokens provides a mock function with given fields: ctx
func (_m *MockClientAPI) GetTrendingTokens(ctx context.Context) (*birdeye.TokenTrendingResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTrendingTokens")
	}

	var r0 *birdeye.TokenTrendingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*birdeye.TokenTrendingResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *birdeye.TokenTrendingResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*birdeye.TokenTrendingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientAPI_GetTrendingTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrendingTokens'
type MockClientAPI_GetTrendingTokens_Call struct {
	*mock.Call
}

// GetTrendingTokens is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientAPI_Expecter) GetTrendingTokens(ctx interface{}) *MockClientAPI_GetTrendingTokens_Call {
	return &MockClientAPI_GetTrendingTokens_Call{Call: _e.mock.On("GetTrendingTokens", ctx)}
}

func (_c *MockClientAPI_GetTrendingTokens_Call) Run(run func(ctx context.Context)) *MockClientAPI_GetTrendingTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClientAPI_GetTrendingTokens_Call) Return(_a0 *birdeye.TokenTrendingResponse, _a1 error) *MockClientAPI_GetTrendingTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientAPI_GetTrendingTokens_Call) RunAndReturn(run func(context.Context) (*birdeye.TokenTrendingResponse, error)) *MockClientAPI_GetTrendingTokens_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientAPI creates a new instance of MockClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientAPI {
	mock := &MockClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
