// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package birdeyemocks

import (
	"context"

	"github.com/nicolas-martin/dankfolio/backend/internal/clients/birdeye"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientAPI creates a new instance of MockClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientAPI {
	mock := &MockClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientAPI is an autogenerated mock type for the ClientAPI type
type MockClientAPI struct {
	mock.Mock
}

type MockClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientAPI) EXPECT() *MockClientAPI_Expecter {
	return &MockClientAPI_Expecter{mock: &_m.Mock}
}

// GetNewListingTokens provides a mock function for the type MockClientAPI
func (_mock *MockClientAPI) GetNewListingTokens(ctx context.Context, params birdeye.NewListingTokensParams) (*birdeye.NewListingTokensResponse, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetNewListingTokens")
	}

	var r0 *birdeye.NewListingTokensResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, birdeye.NewListingTokensParams) (*birdeye.NewListingTokensResponse, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, birdeye.NewListingTokensParams) *birdeye.NewListingTokensResponse); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*birdeye.NewListingTokensResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, birdeye.NewListingTokensParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAPI_GetNewListingTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewListingTokens'
type MockClientAPI_GetNewListingTokens_Call struct {
	*mock.Call
}

// GetNewListingTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - params birdeye.NewListingTokensParams
func (_e *MockClientAPI_Expecter) GetNewListingTokens(ctx interface{}, params interface{}) *MockClientAPI_GetNewListingTokens_Call {
	return &MockClientAPI_GetNewListingTokens_Call{Call: _e.mock.On("GetNewListingTokens", ctx, params)}
}

func (_c *MockClientAPI_GetNewListingTokens_Call) Run(run func(ctx context.Context, params birdeye.NewListingTokensParams)) *MockClientAPI_GetNewListingTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 birdeye.NewListingTokensParams
		if args[1] != nil {
			arg1 = args[1].(birdeye.NewListingTokensParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientAPI_GetNewListingTokens_Call) Return(newListingTokensResponse *birdeye.NewListingTokensResponse, err error) *MockClientAPI_GetNewListingTokens_Call {
	_c.Call.Return(newListingTokensResponse, err)
	return _c
}

func (_c *MockClientAPI_GetNewListingTokens_Call) RunAndReturn(run func(ctx context.Context, params birdeye.NewListingTokensParams) (*birdeye.NewListingTokensResponse, error)) *MockClientAPI_GetNewListingTokens_Call {
	_c.Call.Return(run)
	return _c
}

// GetPriceHistory provides a mock function for the type MockClientAPI
func (_mock *MockClientAPI) GetPriceHistory(ctx context.Context, params birdeye.PriceHistoryParams) (*birdeye.PriceHistory, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceHistory")
	}

	var r0 *birdeye.PriceHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, birdeye.PriceHistoryParams) (*birdeye.PriceHistory, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, birdeye.PriceHistoryParams) *birdeye.PriceHistory); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*birdeye.PriceHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, birdeye.PriceHistoryParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAPI_GetPriceHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceHistory'
type MockClientAPI_GetPriceHistory_Call struct {
	*mock.Call
}

// GetPriceHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - params birdeye.PriceHistoryParams
func (_e *MockClientAPI_Expecter) GetPriceHistory(ctx interface{}, params interface{}) *MockClientAPI_GetPriceHistory_Call {
	return &MockClientAPI_GetPriceHistory_Call{Call: _e.mock.On("GetPriceHistory", ctx, params)}
}

func (_c *MockClientAPI_GetPriceHistory_Call) Run(run func(ctx context.Context, params birdeye.PriceHistoryParams)) *MockClientAPI_GetPriceHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 birdeye.PriceHistoryParams
		if args[1] != nil {
			arg1 = args[1].(birdeye.PriceHistoryParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientAPI_GetPriceHistory_Call) Return(priceHistory *birdeye.PriceHistory, err error) *MockClientAPI_GetPriceHistory_Call {
	_c.Call.Return(priceHistory, err)
	return _c
}

func (_c *MockClientAPI_GetPriceHistory_Call) RunAndReturn(run func(ctx context.Context, params birdeye.PriceHistoryParams) (*birdeye.PriceHistory, error)) *MockClientAPI_GetPriceHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenOverview provides a mock function for the type MockClientAPI
func (_mock *MockClientAPI) GetTokenOverview(ctx context.Context, address string) (*birdeye.TokenOverview, error) {
	ret := _mock.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenOverview")
	}

	var r0 *birdeye.TokenOverview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*birdeye.TokenOverview, error)); ok {
		return returnFunc(ctx, address)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *birdeye.TokenOverview); ok {
		r0 = returnFunc(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*birdeye.TokenOverview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, address)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAPI_GetTokenOverview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenOverview'
type MockClientAPI_GetTokenOverview_Call struct {
	*mock.Call
}

// GetTokenOverview is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
func (_e *MockClientAPI_Expecter) GetTokenOverview(ctx interface{}, address interface{}) *MockClientAPI_GetTokenOverview_Call {
	return &MockClientAPI_GetTokenOverview_Call{Call: _e.mock.On("GetTokenOverview", ctx, address)}
}

func (_c *MockClientAPI_GetTokenOverview_Call) Run(run func(ctx context.Context, address string)) *MockClientAPI_GetTokenOverview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientAPI_GetTokenOverview_Call) Return(tokenOverview *birdeye.TokenOverview, err error) *MockClientAPI_GetTokenOverview_Call {
	_c.Call.Return(tokenOverview, err)
	return _c
}

func (_c *MockClientAPI_GetTokenOverview_Call) RunAndReturn(run func(ctx context.Context, address string) (*birdeye.TokenOverview, error)) *MockClientAPI_GetTokenOverview_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokensOverviewBatch provides a mock function for the type MockClientAPI
func (_mock *MockClientAPI) GetTokensOverviewBatch(ctx context.Context, addresses []string) ([]birdeye.TokenOverviewData, error) {
	ret := _mock.Called(ctx, addresses)

	if len(ret) == 0 {
		panic("no return value specified for GetTokensOverviewBatch")
	}

	var r0 []birdeye.TokenOverviewData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]birdeye.TokenOverviewData, error)); ok {
		return returnFunc(ctx, addresses)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []birdeye.TokenOverviewData); ok {
		r0 = returnFunc(ctx, addresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]birdeye.TokenOverviewData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, addresses)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAPI_GetTokensOverviewBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokensOverviewBatch'
type MockClientAPI_GetTokensOverviewBatch_Call struct {
	*mock.Call
}

// GetTokensOverviewBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - addresses []string
func (_e *MockClientAPI_Expecter) GetTokensOverviewBatch(ctx interface{}, addresses interface{}) *MockClientAPI_GetTokensOverviewBatch_Call {
	return &MockClientAPI_GetTokensOverviewBatch_Call{Call: _e.mock.On("GetTokensOverviewBatch", ctx, addresses)}
}

func (_c *MockClientAPI_GetTokensOverviewBatch_Call) Run(run func(ctx context.Context, addresses []string)) *MockClientAPI_GetTokensOverviewBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientAPI_GetTokensOverviewBatch_Call) Return(tokenOverviewDatas []birdeye.TokenOverviewData, err error) *MockClientAPI_GetTokensOverviewBatch_Call {
	_c.Call.Return(tokenOverviewDatas, err)
	return _c
}

func (_c *MockClientAPI_GetTokensOverviewBatch_Call) RunAndReturn(run func(ctx context.Context, addresses []string) ([]birdeye.TokenOverviewData, error)) *MockClientAPI_GetTokensOverviewBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokensTradeDataBatch provides a mock function for the type MockClientAPI
func (_mock *MockClientAPI) GetTokensTradeDataBatch(ctx context.Context, addresses []string) ([]birdeye.TokenTradeData, error) {
	ret := _mock.Called(ctx, addresses)

	if len(ret) == 0 {
		panic("no return value specified for GetTokensTradeDataBatch")
	}

	var r0 []birdeye.TokenTradeData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]birdeye.TokenTradeData, error)); ok {
		return returnFunc(ctx, addresses)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []birdeye.TokenTradeData); ok {
		r0 = returnFunc(ctx, addresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]birdeye.TokenTradeData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, addresses)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAPI_GetTokensTradeDataBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokensTradeDataBatch'
type MockClientAPI_GetTokensTradeDataBatch_Call struct {
	*mock.Call
}

// GetTokensTradeDataBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - addresses []string
func (_e *MockClientAPI_Expecter) GetTokensTradeDataBatch(ctx interface{}, addresses interface{}) *MockClientAPI_GetTokensTradeDataBatch_Call {
	return &MockClientAPI_GetTokensTradeDataBatch_Call{Call: _e.mock.On("GetTokensTradeDataBatch", ctx, addresses)}
}

func (_c *MockClientAPI_GetTokensTradeDataBatch_Call) Run(run func(ctx context.Context, addresses []string)) *MockClientAPI_GetTokensTradeDataBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientAPI_GetTokensTradeDataBatch_Call) Return(tokenTradeDatas []birdeye.TokenTradeData, err error) *MockClientAPI_GetTokensTradeDataBatch_Call {
	_c.Call.Return(tokenTradeDatas, err)
	return _c
}

func (_c *MockClientAPI_GetTokensTradeDataBatch_Call) RunAndReturn(run func(ctx context.Context, addresses []string) ([]birdeye.TokenTradeData, error)) *MockClientAPI_GetTokensTradeDataBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrendingTokens provides a mock function for the type MockClientAPI
func (_mock *MockClientAPI) GetTrendingTokens(ctx context.Context, params birdeye.TrendingTokensParams) (*birdeye.TokenTrendingResponse, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetTrendingTokens")
	}

	var r0 *birdeye.TokenTrendingResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, birdeye.TrendingTokensParams) (*birdeye.TokenTrendingResponse, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, birdeye.TrendingTokensParams) *birdeye.TokenTrendingResponse); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*birdeye.TokenTrendingResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, birdeye.TrendingTokensParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAPI_GetTrendingTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrendingTokens'
type MockClientAPI_GetTrendingTokens_Call struct {
	*mock.Call
}

// GetTrendingTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - params birdeye.TrendingTokensParams
func (_e *MockClientAPI_Expecter) GetTrendingTokens(ctx interface{}, params interface{}) *MockClientAPI_GetTrendingTokens_Call {
	return &MockClientAPI_GetTrendingTokens_Call{Call: _e.mock.On("GetTrendingTokens", ctx, params)}
}

func (_c *MockClientAPI_GetTrendingTokens_Call) Run(run func(ctx context.Context, params birdeye.TrendingTokensParams)) *MockClientAPI_GetTrendingTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 birdeye.TrendingTokensParams
		if args[1] != nil {
			arg1 = args[1].(birdeye.TrendingTokensParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientAPI_GetTrendingTokens_Call) Return(tokenTrendingResponse *birdeye.TokenTrendingResponse, err error) *MockClientAPI_GetTrendingTokens_Call {
	_c.Call.Return(tokenTrendingResponse, err)
	return _c
}

func (_c *MockClientAPI_GetTrendingTokens_Call) RunAndReturn(run func(ctx context.Context, params birdeye.TrendingTokensParams) (*birdeye.TokenTrendingResponse, error)) *MockClientAPI_GetTrendingTokens_Call {
	_c.Call.Return(run)
	return _c
}
