// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package telemetrymocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTelemetryAPI creates a new instance of MockTelemetryAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelemetryAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelemetryAPI {
	mock := &MockTelemetryAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTelemetryAPI is an autogenerated mock type for the TelemetryAPI type
type MockTelemetryAPI struct {
	mock.Mock
}

type MockTelemetryAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelemetryAPI) EXPECT() *MockTelemetryAPI_Expecter {
	return &MockTelemetryAPI_Expecter{mock: &_m.Mock}
}

// GetStats provides a mock function for the type MockTelemetryAPI
func (_mock *MockTelemetryAPI) GetStats() map[string]map[string]int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 map[string]map[string]int
	if returnFunc, ok := ret.Get(0).(func() map[string]map[string]int); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]map[string]int)
		}
	}
	return r0
}

// MockTelemetryAPI_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockTelemetryAPI_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
func (_e *MockTelemetryAPI_Expecter) GetStats() *MockTelemetryAPI_GetStats_Call {
	return &MockTelemetryAPI_GetStats_Call{Call: _e.mock.On("GetStats")}
}

func (_c *MockTelemetryAPI_GetStats_Call) Run(run func()) *MockTelemetryAPI_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTelemetryAPI_GetStats_Call) Return(stringToStringToInt map[string]map[string]int) *MockTelemetryAPI_GetStats_Call {
	_c.Call.Return(stringToStringToInt)
	return _c
}

func (_c *MockTelemetryAPI_GetStats_Call) RunAndReturn(run func() map[string]map[string]int) *MockTelemetryAPI_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// LoadStatsForToday provides a mock function for the type MockTelemetryAPI
func (_mock *MockTelemetryAPI) LoadStatsForToday(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadStatsForToday")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTelemetryAPI_LoadStatsForToday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadStatsForToday'
type MockTelemetryAPI_LoadStatsForToday_Call struct {
	*mock.Call
}

// LoadStatsForToday is a helper method to define mock.On call
//   - ctx
func (_e *MockTelemetryAPI_Expecter) LoadStatsForToday(ctx interface{}) *MockTelemetryAPI_LoadStatsForToday_Call {
	return &MockTelemetryAPI_LoadStatsForToday_Call{Call: _e.mock.On("LoadStatsForToday", ctx)}
}

func (_c *MockTelemetryAPI_LoadStatsForToday_Call) Run(run func(ctx context.Context)) *MockTelemetryAPI_LoadStatsForToday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTelemetryAPI_LoadStatsForToday_Call) Return(err error) *MockTelemetryAPI_LoadStatsForToday_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTelemetryAPI_LoadStatsForToday_Call) RunAndReturn(run func(ctx context.Context) error) *MockTelemetryAPI_LoadStatsForToday_Call {
	_c.Call.Return(run)
	return _c
}

// ResetStats provides a mock function for the type MockTelemetryAPI
func (_mock *MockTelemetryAPI) ResetStats(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ResetStats")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTelemetryAPI_ResetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetStats'
type MockTelemetryAPI_ResetStats_Call struct {
	*mock.Call
}

// ResetStats is a helper method to define mock.On call
//   - ctx
func (_e *MockTelemetryAPI_Expecter) ResetStats(ctx interface{}) *MockTelemetryAPI_ResetStats_Call {
	return &MockTelemetryAPI_ResetStats_Call{Call: _e.mock.On("ResetStats", ctx)}
}

func (_c *MockTelemetryAPI_ResetStats_Call) Run(run func(ctx context.Context)) *MockTelemetryAPI_ResetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTelemetryAPI_ResetStats_Call) Return(err error) *MockTelemetryAPI_ResetStats_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTelemetryAPI_ResetStats_Call) RunAndReturn(run func(ctx context.Context) error) *MockTelemetryAPI_ResetStats_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockTelemetryAPI
func (_mock *MockTelemetryAPI) Start(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockTelemetryAPI_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockTelemetryAPI_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx
func (_e *MockTelemetryAPI_Expecter) Start(ctx interface{}) *MockTelemetryAPI_Start_Call {
	return &MockTelemetryAPI_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockTelemetryAPI_Start_Call) Run(run func(ctx context.Context)) *MockTelemetryAPI_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTelemetryAPI_Start_Call) Return() *MockTelemetryAPI_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTelemetryAPI_Start_Call) RunAndReturn(run func(ctx context.Context)) *MockTelemetryAPI_Start_Call {
	_c.Run(run)
	return _c
}

// TrackCall provides a mock function for the type MockTelemetryAPI
func (_mock *MockTelemetryAPI) TrackCall(serviceName string, endpointName string) {
	_mock.Called(serviceName, endpointName)
	return
}

// MockTelemetryAPI_TrackCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackCall'
type MockTelemetryAPI_TrackCall_Call struct {
	*mock.Call
}

// TrackCall is a helper method to define mock.On call
//   - serviceName
//   - endpointName
func (_e *MockTelemetryAPI_Expecter) TrackCall(serviceName interface{}, endpointName interface{}) *MockTelemetryAPI_TrackCall_Call {
	return &MockTelemetryAPI_TrackCall_Call{Call: _e.mock.On("TrackCall", serviceName, endpointName)}
}

func (_c *MockTelemetryAPI_TrackCall_Call) Run(run func(serviceName string, endpointName string)) *MockTelemetryAPI_TrackCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockTelemetryAPI_TrackCall_Call) Return() *MockTelemetryAPI_TrackCall_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTelemetryAPI_TrackCall_Call) RunAndReturn(run func(serviceName string, endpointName string)) *MockTelemetryAPI_TrackCall_Call {
	_c.Run(run)
	return _c
}
